// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void fnscrmainbatterybuttonclicked(lv_event_t * e);
void fnscrmainmanualbuttonclicked(lv_event_t * e);
void fnscrdetailbatterybuttonclicked(lv_event_t * e);
void fnscrdetailmanualbuttonclicked(lv_event_t * e);
void fnscrdetailbackslotbuttonclicked(lv_event_t * e);
void fnscrdetailnextslotbuttonclicked(lv_event_t * e);
void fnscrdetailbacktomainbuttonclicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
