// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void fnscrmainbatterybuttonclicked(lv_event_t * e);
void fnscrmainmanualbuttonclicked(lv_event_t * e);
void backtomainscrevt(lv_event_t * e);
void scrprocessprbuttonclicked(lv_event_t * e);
void scrprocessstbuttonclicked(lv_event_t * e);
void fnscrmanual1selectbat1(lv_event_t * e);
void fnscrmanual1selectbat2(lv_event_t * e);
void fnscrmanual1selectslot1(lv_event_t * e);
void fnscrmanual1selectslot2(lv_event_t * e);
void fnscrmanual1selectslot3(lv_event_t * e);
void fnscrmanual1selectslot4(lv_event_t * e);
void fnscrmanual1selectslot5(lv_event_t * e);
void fnscrdetailnextslotgasture(lv_event_t * e);
void fnscrdetailbackslotgasture(lv_event_t * e);
void fnscrdetailbatterybuttonclicked(lv_event_t * e);
void fnscrdetailmanualbuttonclicked(lv_event_t * e);
void fnbacktomainbutton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
