// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "ui.h"

void fnMainChangeSettingClicked(lv_event_t * e)
{
	// Your code here
}

void fnSettingBackToMainClicked(lv_event_t * e)
{
	// Your code here
}
