// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

// COMPONENT buttoncontainer

lv_obj_t * ui_buttoncontainer_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_buttoncontainer;
    cui_buttoncontainer = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_buttoncontainer);
    lv_obj_set_width(cui_buttoncontainer, 180);
    lv_obj_set_height(cui_buttoncontainer, 70);
    lv_obj_set_x(cui_buttoncontainer, 238);
    lv_obj_set_y(cui_buttoncontainer, -40);
    lv_obj_set_align(cui_buttoncontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_buttoncontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_button;
    cui_button = lv_btn_create(cui_buttoncontainer);
    lv_obj_set_width(cui_button, 178);
    lv_obj_set_height(cui_button, 65);
    lv_obj_set_x(cui_button, -1);
    lv_obj_set_y(cui_button, -2);
    lv_obj_set_align(cui_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(cui_button, lv_color_hex(0x898989), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_button, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(cui_button, lv_color_hex(0x38E868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_butonlabel;
    cui_butonlabel = lv_label_create(cui_buttoncontainer);
    lv_obj_set_width(cui_butonlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_butonlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_butonlabel, 2);
    lv_obj_set_y(cui_butonlabel, -1);
    lv_obj_set_align(cui_butonlabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_butonlabel, "Battery 1");
    lv_obj_set_style_text_color(cui_butonlabel, lv_color_hex(0xE7E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_butonlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_butonlabel, &ui_font_Light, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTONCONTAINER_NUM);
    children[UI_COMP_BUTTONCONTAINER_BUTTONCONTAINER] = cui_buttoncontainer;
    children[UI_COMP_BUTTONCONTAINER_BUTTON] = cui_button;
    children[UI_COMP_BUTTONCONTAINER_BUTONLABEL] = cui_butonlabel;
    lv_obj_add_event_cb(cui_buttoncontainer, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_buttoncontainer, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_buttoncontainer_create_hook(cui_buttoncontainer);
    return cui_buttoncontainer;
}

