// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef _UI_COMP_BUTTONCONTAINER_H
#define _UI_COMP_BUTTONCONTAINER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT buttoncontainer
#define UI_COMP_BUTTONCONTAINER_BUTTONCONTAINER 0
#define UI_COMP_BUTTONCONTAINER_BUTTON 1
#define UI_COMP_BUTTONCONTAINER_BUTONLABEL 2
#define _UI_COMP_BUTTONCONTAINER_NUM 3
lv_obj_t * ui_buttoncontainer_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
