// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_imgMainBackground;
extern lv_obj_t * ui_lbMainTitle;
extern void ui_event_ibtMainToSetting(lv_event_t * e);
extern lv_obj_t * ui_ibtMainToSetting;
extern lv_obj_t * ui_imgMainSlotSerialDetail1;
extern lv_obj_t * ui_imgMainSlotSerialDetail2;
extern lv_obj_t * ui_imgMainSlotSerialDetail3;
extern lv_obj_t * ui_imgMainSlotSerialDetail4;
extern lv_obj_t * ui_imgMainSlotSerialDetail5;
extern lv_obj_t * ui_btMainSlot1;
extern lv_obj_t * ui_btMainSlot2;
extern lv_obj_t * ui_btMainSlot3;
extern lv_obj_t * ui_btMainSlot4;
extern lv_obj_t * ui_btMainSlot5;
extern lv_obj_t * ui_imgMainEmptyBat1;
extern lv_obj_t * ui_imgMainEmptyBat2;
extern lv_obj_t * ui_imgMainEmptyBat3;
extern lv_obj_t * ui_imgMainEmptyBat4;
extern lv_obj_t * ui_imgMainEmptyBat5;
extern lv_obj_t * ui_barMainBatPercent1;
extern lv_obj_t * ui_barMainBatPercent2;
extern lv_obj_t * ui_barMainBatPercent3;
extern lv_obj_t * ui_barMainBatPercent4;
extern lv_obj_t * ui_barMainBatPercent5;
extern lv_obj_t * ui_imgMainBatWarn1;
extern lv_obj_t * ui_imgMainBatWarn2;
extern lv_obj_t * ui_imgMainBatWarn3;
extern lv_obj_t * ui_imgMainBatWarn4;
extern lv_obj_t * ui_imgMainBatWarn5;
extern lv_obj_t * ui_lbMainSlot1SOC;
extern lv_obj_t * ui_lbMainSlot2SOC;
extern lv_obj_t * ui_lbMainSlot3SOC;
extern lv_obj_t * ui_lbMainSlot4SOC;
extern lv_obj_t * ui_lbMainSlot5SOC;
extern lv_obj_t * ui_lbMainVoltageSlot1;
extern lv_obj_t * ui_lbMainVoltageSlot2;
extern lv_obj_t * ui_lbMainVoltageSlot3;
extern lv_obj_t * ui_lbMainVoltageSlot4;
extern lv_obj_t * ui_lbMainVoltageSlot5;
extern lv_obj_t * ui_lbMainCapSlot1;
extern lv_obj_t * ui_lbMainCapSlot2;
extern lv_obj_t * ui_lbMainCapSlot3;
extern lv_obj_t * ui_lbMainCapSlot4;
extern lv_obj_t * ui_lbMainCapSlot5;
extern lv_obj_t * ui_imgMainSlotDetalBg;
extern lv_obj_t * ui_lbMainSlotBMSState;
extern lv_obj_t * ui_lbMainSlotBMSStateValue;
extern lv_obj_t * ui_lbMainSlotCtrlRq;
extern lv_obj_t * ui_lbMainSlotCtrlRqValue;
extern lv_obj_t * ui_lbMainSlotCtrlRp;
extern lv_obj_t * ui_lbMainSlotCtrlRpValue;
extern lv_obj_t * ui_lbMainSlotFETCtrlP;
extern lv_obj_t * ui_lbMainSlotFETCtrlPValue;
extern lv_obj_t * ui_lbMainSlotFETStt;
extern lv_obj_t * ui_lbMainSlotFETSttValue;
extern lv_obj_t * ui_lbMainSlotAlarmBits;
extern lv_obj_t * ui_lbMainSlotAlarmBitsValue;
extern lv_obj_t * ui_lbMainSlotFault;
extern lv_obj_t * ui_lbMainSlotFaultValue;
extern lv_obj_t * ui_lbMainSlotPackVolt;
extern lv_obj_t * ui_lbMainSlotPackVoltValue;
extern lv_obj_t * ui_lbMainSlotStackVolt;
extern lv_obj_t * ui_lbMainSlotStackVoltValue;
extern lv_obj_t * ui_lbMainSlotPackCur;
extern lv_obj_t * ui_lbMainSlotPackCurValue;
extern lv_obj_t * ui_lbMainSlotIdVolt;
extern lv_obj_t * ui_lbMainSlotIdVoltValue;
extern lv_obj_t * ui_lbMainSlotPinPercent;
extern lv_obj_t * ui_lbMainSlotPinPercentValue;
extern lv_obj_t * ui_lbMainSlotTgPercent;
extern lv_obj_t * ui_lbMainSlotTgPercentValue;
extern lv_obj_t * ui_lbMainSlotCelRes;
extern lv_obj_t * ui_lbMainSlotCelResValue;
extern lv_obj_t * ui_lbMainSlotSocPer;
extern lv_obj_t * ui_lbMainSlotSocPerValue;
extern lv_obj_t * ui_lbMainSlotSOH;
extern lv_obj_t * ui_lbMainSlotSOHValue;
extern lv_obj_t * ui_lbMainSlotSinPar;
extern lv_obj_t * ui_lbMainSlotSinParValue;
extern lv_obj_t * ui_lbMainSlotTemp1;
extern lv_obj_t * ui_lbMainSlotTemp1Value;
extern lv_obj_t * ui_lbMainSlotTemp2;
extern lv_obj_t * ui_lbMainSlotTemp2Value;
extern lv_obj_t * ui_lbMainSlotTemp3;
extern lv_obj_t * ui_lbMainSlotTemp3Value;
extern lv_obj_t * ui_lbMainSlotCell1;
extern lv_obj_t * ui_lbMainSlotCell1Value;
extern lv_obj_t * ui_lbMainSlotCell2;
extern lv_obj_t * ui_lbMainSlotCell2Value;
extern lv_obj_t * ui_lbMainSlotCell3;
extern lv_obj_t * ui_lbMainSlotCell3Value;
extern lv_obj_t * ui_lbMainSlotCell4;
extern lv_obj_t * ui_lbMainSlotCell4Value;
extern lv_obj_t * ui_lbMainSlotCell5;
extern lv_obj_t * ui_lbMainSlotCell5Value;
extern lv_obj_t * ui_lbMainSlotCell6;
extern lv_obj_t * ui_lbMainSlotCell6Value;
extern lv_obj_t * ui_lbMainSlotCell7;
extern lv_obj_t * ui_lbMainSlotCell7Value;
extern lv_obj_t * ui_lbMainSlotCell8;
extern lv_obj_t * ui_lbMainSlotCell8Value;
extern lv_obj_t * ui_lbMainSlotCell9;
extern lv_obj_t * ui_lbMainSlotCell9Value;
extern lv_obj_t * ui_lbMainSlotCell10;
extern lv_obj_t * ui_lbMainSlotCell10Value;
extern lv_obj_t * ui_lbMainSlotCell11;
extern lv_obj_t * ui_lbMainSlotCell11Value;
extern lv_obj_t * ui_lbMainSlotCell12;
extern lv_obj_t * ui_lbMainSlotCell12Value;
extern lv_obj_t * ui_lbMainSlotCell13;
extern lv_obj_t * ui_lbMainSlotCell13Value;
extern lv_obj_t * ui_lbMainSlotACCUInt;
extern lv_obj_t * ui_lbMainSlotACCUIntValue;
extern lv_obj_t * ui_lbMainSlotACCUFrac;
extern lv_obj_t * ui_lbMainSlotACCUFracValue;
extern lv_obj_t * ui_lbMainSlotACCUTime;
extern lv_obj_t * ui_lbMainSlotACCUTimeValue;
extern lv_obj_t * ui_lbMainSlotSafetyA;
extern lv_obj_t * ui_lbMainSlotSafetyAValue;
extern lv_obj_t * ui_lbMainSlotSafetyB;
extern lv_obj_t * ui_lbMainSlotSafetyBValue;
extern lv_obj_t * ui_lbMainSlotSafetyC;
extern lv_obj_t * ui_lbMainSlotSafetyCValue;
extern lv_obj_t * ui_ibtMainManualSwap;
extern lv_obj_t * ui_imgMainBotbotEmptyPin;
extern lv_obj_t * ui_imgMainRobotFullPin;
extern lv_obj_t * ui_imgMainRobotCharging;
extern lv_obj_t * ui_imgMainRbToSlot1;
extern lv_obj_t * ui_imgMainRbToSlot2;
extern lv_obj_t * ui_imgMainRbToSlot3;
extern lv_obj_t * ui_imgMainRbToSlot4;
extern lv_obj_t * ui_imgMainRbToSlot5;
extern lv_obj_t * ui_imgMainBattery;
extern lv_obj_t * ui_imgMainNotConnect;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

