// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRSPLASH_H
#define UI_SCRSPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrSplash
extern void ui_scrSplash_screen_init(void);
extern void ui_scrSplash_screen_destroy(void);
extern void ui_event_scrSplash(lv_event_t * e);
extern lv_obj_t * ui_scrSplash;
extern lv_obj_t * ui_scrsplashloadingbar;
extern lv_obj_t * ui_scrsplashloadingprogresslabel;
extern lv_obj_t * ui_scrsplashvmologo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

