// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_scrManualControl22 = NULL;
lv_obj_t * ui_scrmanual2robotnchrgimg = NULL;
lv_obj_t * ui_scrmanual2guidelabel = NULL;
lv_obj_t * ui_scrmanual2vmologo = NULL;
lv_obj_t * ui_scrmanual2backtomainbutton = NULL;
lv_obj_t * ui_scrmanual2btgrpcontainer = NULL;
lv_obj_t * ui_chooses1container = NULL;
lv_obj_t * ui_chooses2container = NULL;
lv_obj_t * ui_chooses3container = NULL;
lv_obj_t * ui_chooses4container = NULL;
lv_obj_t * ui_chooses5container = NULL;
lv_obj_t * ui_scrmanual2slotinfolabel = NULL;
// event funtions
void ui_event_scrManualControl22(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        fadeout_Animation(ui_scrmanual2robotnchrgimg, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        _ui_opacity_set(ui_scrmanual2robotnchrgimg, 255);
    }
}

void ui_event_scrmanual2backtomainbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_chooses1container_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrProcess, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_scrProcess_screen_init);
    }
}

void ui_event_chooses2container_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrProcess, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_scrProcess_screen_init);
    }
}

void ui_event_chooses3container_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrProcess, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_scrProcess_screen_init);
    }
}

void ui_event_chooses4container_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrProcess, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_scrProcess_screen_init);
    }
}

void ui_event_chooses5container_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrProcess, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_scrProcess_screen_init);
    }
}

// build funtions

void ui_scrManualControl22_screen_init(void)
{
    ui_scrManualControl22 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrManualControl22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrManualControl22, &ui_img_143516147, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrmanual2robotnchrgimg = lv_img_create(ui_scrManualControl22);
    lv_img_set_src(ui_scrmanual2robotnchrgimg, &ui_img_z7358953714029_6a7a8c912df9884a2fa156d0bc4a5d11_1_png);
    lv_obj_set_width(ui_scrmanual2robotnchrgimg, LV_SIZE_CONTENT);   /// 487
    lv_obj_set_height(ui_scrmanual2robotnchrgimg, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_scrmanual2robotnchrgimg, 155);
    lv_obj_set_y(ui_scrmanual2robotnchrgimg, 0);
    lv_obj_set_align(ui_scrmanual2robotnchrgimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrmanual2robotnchrgimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrmanual2robotnchrgimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_scrmanual2robotnchrgimg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrmanual2guidelabel = lv_label_create(ui_scrManualControl22);
    lv_obj_set_width(ui_scrmanual2guidelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrmanual2guidelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrmanual2guidelabel, -254);
    lv_obj_set_y(ui_scrmanual2guidelabel, -187);
    lv_obj_set_align(ui_scrmanual2guidelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrmanual2guidelabel, "STEP 2/2: \nSELECT BATTERY \nON THE CHARGER");
    lv_obj_set_style_text_color(ui_scrmanual2guidelabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrmanual2guidelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_scrmanual2guidelabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrmanual2guidelabel, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrmanual2vmologo = lv_img_create(ui_scrManualControl22);
    lv_img_set_src(ui_scrmanual2vmologo, &ui_img_vmo_logo2_png);
    lv_obj_set_width(ui_scrmanual2vmologo, LV_SIZE_CONTENT);   /// 216
    lv_obj_set_height(ui_scrmanual2vmologo, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_scrmanual2vmologo, 289);
    lv_obj_set_y(ui_scrmanual2vmologo, 218);
    lv_obj_set_align(ui_scrmanual2vmologo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrmanual2vmologo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrmanual2vmologo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrmanual2backtomainbutton = lv_btn_create(ui_scrManualControl22);
    lv_obj_set_width(ui_scrmanual2backtomainbutton, 230);
    lv_obj_set_height(ui_scrmanual2backtomainbutton, 50);
    lv_obj_set_x(ui_scrmanual2backtomainbutton, 282);
    lv_obj_set_y(ui_scrmanual2backtomainbutton, 212);
    lv_obj_set_align(ui_scrmanual2backtomainbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrmanual2backtomainbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_scrmanual2backtomainbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_scrmanual2backtomainbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrmanual2btgrpcontainer = lv_obj_create(ui_scrManualControl22);
    lv_obj_remove_style_all(ui_scrmanual2btgrpcontainer);
    lv_obj_set_width(ui_scrmanual2btgrpcontainer, 189);
    lv_obj_set_height(ui_scrmanual2btgrpcontainer, 375);
    lv_obj_set_x(ui_scrmanual2btgrpcontainer, 22);
    lv_obj_set_y(ui_scrmanual2btgrpcontainer, 40);
    lv_obj_set_align(ui_scrmanual2btgrpcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrmanual2btgrpcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chooses1container = ui_buttoncontainer_create(ui_scrmanual2btgrpcontainer);
    lv_obj_set_x(ui_chooses1container, 0);
    lv_obj_set_y(ui_chooses1container, -148);

    lv_label_set_text(ui_comp_get_child(ui_chooses1container, UI_COMP_BUTTONCONTAINER_BUTONLABEL), "SLOT 1");

    ui_chooses2container = ui_buttoncontainer_create(ui_scrmanual2btgrpcontainer);
    lv_obj_set_x(ui_chooses2container, 0);
    lv_obj_set_y(ui_chooses2container, -74);

    lv_label_set_text(ui_comp_get_child(ui_chooses2container, UI_COMP_BUTTONCONTAINER_BUTONLABEL), "SLOT 2");

    ui_chooses3container = ui_buttoncontainer_create(ui_scrmanual2btgrpcontainer);
    lv_obj_set_x(ui_chooses3container, 0);
    lv_obj_set_y(ui_chooses3container, 0);

    lv_label_set_text(ui_comp_get_child(ui_chooses3container, UI_COMP_BUTTONCONTAINER_BUTONLABEL), "SLOT 3");

    ui_chooses4container = ui_buttoncontainer_create(ui_scrmanual2btgrpcontainer);
    lv_obj_set_x(ui_chooses4container, 0);
    lv_obj_set_y(ui_chooses4container, 74);

    lv_label_set_text(ui_comp_get_child(ui_chooses4container, UI_COMP_BUTTONCONTAINER_BUTONLABEL), "SLOT 4");

    ui_chooses5container = ui_buttoncontainer_create(ui_scrmanual2btgrpcontainer);
    lv_obj_set_x(ui_chooses5container, 0);
    lv_obj_set_y(ui_chooses5container, 149);

    lv_label_set_text(ui_comp_get_child(ui_chooses5container, UI_COMP_BUTTONCONTAINER_BUTONLABEL), "SLOT 5");

    ui_scrmanual2slotinfolabel = lv_label_create(ui_scrManualControl22);
    lv_obj_set_width(ui_scrmanual2slotinfolabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrmanual2slotinfolabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrmanual2slotinfolabel, -144);
    lv_obj_set_y(ui_scrmanual2slotinfolabel, 42);
    lv_obj_set_align(ui_scrmanual2slotinfolabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrmanual2slotinfolabel, "-.-V\n-.-%\n\n-.-V\n-.-%\n\n-.-V\n-.-%\n\n-.-V\n-.-%\n\n-.-V\n-.-%");
    lv_obj_set_style_text_align(ui_scrmanual2slotinfolabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrmanual2slotinfolabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_scrmanual2backtomainbutton, ui_event_scrmanual2backtomainbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_chooses1container, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_chooses1container_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_chooses2container, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_chooses2container_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_chooses3container, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_chooses3container_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_chooses4container, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_chooses4container_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_chooses5container, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_chooses5container_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrManualControl22, ui_event_scrManualControl22, LV_EVENT_ALL, NULL);

}

void ui_scrManualControl22_screen_destroy(void)
{
    if(ui_scrManualControl22) lv_obj_del(ui_scrManualControl22);

    // NULL screen variables
    ui_scrManualControl22 = NULL;
    ui_scrmanual2robotnchrgimg = NULL;
    ui_scrmanual2guidelabel = NULL;
    ui_scrmanual2vmologo = NULL;
    ui_scrmanual2backtomainbutton = NULL;
    ui_scrmanual2btgrpcontainer = NULL;
    ui_chooses1container = NULL;
    ui_chooses2container = NULL;
    ui_chooses3container = NULL;
    ui_chooses4container = NULL;
    ui_chooses5container = NULL;
    ui_scrmanual2slotinfolabel = NULL;

}
