// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_scrProcess = NULL;
lv_obj_t * ui_scrprocessstatecontainer = NULL;
lv_obj_t * ui_scrprocessstatepanel = NULL;
lv_obj_t * ui_scrprocessstatetitlelabel = NULL;
lv_obj_t * ui_scrprocessstatevalue = NULL;
lv_obj_t * ui_scrprocessvmologo = NULL;
lv_obj_t * ui_scrprocessruntimecontainer = NULL;
lv_obj_t * ui_scrprocessruntimepanel = NULL;
lv_obj_t * ui_scrprocessruntimetitle = NULL;
lv_obj_t * ui_scrprocessruntimevalue = NULL;
lv_obj_t * ui_scrprocessslotssttcontainer = NULL;
lv_obj_t * ui_scrprocessslotssttslot1panel = NULL;
lv_obj_t * ui_scrprocessslotssttslot2panel = NULL;
lv_obj_t * ui_scrprocessslotssttslot3panel = NULL;
lv_obj_t * ui_scrprocessslotssttslot4panel = NULL;
lv_obj_t * ui_scrprocessslotssttslot5panel = NULL;
lv_obj_t * ui_scrprocesschargerimg = NULL;
lv_obj_t * ui_scrprocessrobotimg = NULL;
lv_obj_t * ui_scrprocessbacktomainbutton = NULL;
lv_obj_t * ui_scrprocessprcontainer = NULL;
lv_obj_t * ui_scrprocessstopcontainer = NULL;
// event funtions
void ui_event_scrProcess(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        scrmainstartinvfademove_Animation(ui_scrprocessrobotimg, 0);
        scrsplashstartlogo_Animation(ui_scrprocessstatecontainer, 0);
        scrmainstartfademove_Animation(ui_scrprocessruntimecontainer, 0);
    }
}

void ui_event_scrprocessbacktomainbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrMain_screen_init);
        backtomainscrevt(e);
    }
}

void ui_event_scrprocessprcontainer_scrprocessprcontainer_prbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scrprocessprbuttonclicked(e);
    }
}

void ui_event_scrprocessstopcontainer_scrprocessstopcontainer_stopbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        scrprocessstbuttonclicked(e);
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_scrMain_screen_init);
    }
}

// build funtions

void ui_scrProcess_screen_init(void)
{
    ui_scrProcess = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrProcess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrProcess, &ui_img_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrprocessstatecontainer = lv_obj_create(ui_scrProcess);
    lv_obj_remove_style_all(ui_scrprocessstatecontainer);
    lv_obj_set_width(ui_scrprocessstatecontainer, 268);
    lv_obj_set_height(ui_scrprocessstatecontainer, 132);
    lv_obj_set_x(ui_scrprocessstatecontainer, 257);
    lv_obj_set_y(ui_scrprocessstatecontainer, -166);
    lv_obj_set_align(ui_scrprocessstatecontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrprocessstatecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrprocessstatepanel = lv_obj_create(ui_scrprocessstatecontainer);
    lv_obj_set_width(ui_scrprocessstatepanel, 264);
    lv_obj_set_height(ui_scrprocessstatepanel, 123);
    lv_obj_set_x(ui_scrprocessstatepanel, 1);
    lv_obj_set_y(ui_scrprocessstatepanel, -1);
    lv_obj_set_align(ui_scrprocessstatepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrprocessstatepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrprocessstatepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrprocessstatepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_scrprocessstatepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_scrprocessstatepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrprocessstatepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrprocessstatepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_scrprocessstatepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_scrprocessstatepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrprocessstatetitlelabel = lv_label_create(ui_scrprocessstatecontainer);
    lv_obj_set_width(ui_scrprocessstatetitlelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrprocessstatetitlelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrprocessstatetitlelabel, 0);
    lv_obj_set_y(ui_scrprocessstatetitlelabel, -44);
    lv_obj_set_align(ui_scrprocessstatetitlelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrprocessstatetitlelabel, "State");
    lv_obj_set_style_text_color(ui_scrprocessstatetitlelabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrprocessstatetitlelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_scrprocessstatetitlelabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrprocessstatetitlelabel, &ui_font_H11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrprocessstatevalue = lv_label_create(ui_scrprocessstatecontainer);
    lv_obj_set_width(ui_scrprocessstatevalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrprocessstatevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrprocessstatevalue, 0);
    lv_obj_set_y(ui_scrprocessstatevalue, 7);
    lv_obj_set_align(ui_scrprocessstatevalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrprocessstatevalue, "IDLE");
    lv_obj_set_style_text_color(ui_scrprocessstatevalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrprocessstatevalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrprocessstatevalue, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrprocessvmologo = lv_img_create(ui_scrProcess);
    lv_img_set_src(ui_scrprocessvmologo, &ui_img_vmo_logo2_png);
    lv_obj_set_width(ui_scrprocessvmologo, LV_SIZE_CONTENT);   /// 216
    lv_obj_set_height(ui_scrprocessvmologo, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_scrprocessvmologo, 289);
    lv_obj_set_y(ui_scrprocessvmologo, 218);
    lv_obj_set_align(ui_scrprocessvmologo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrprocessvmologo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrprocessvmologo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrprocessruntimecontainer = lv_obj_create(ui_scrProcess);
    lv_obj_remove_style_all(ui_scrprocessruntimecontainer);
    lv_obj_set_width(ui_scrprocessruntimecontainer, 270);
    lv_obj_set_height(ui_scrprocessruntimecontainer, 117);
    lv_obj_set_x(ui_scrprocessruntimecontainer, -238);
    lv_obj_set_y(ui_scrprocessruntimecontainer, -166);
    lv_obj_set_align(ui_scrprocessruntimecontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrprocessruntimecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrprocessruntimepanel = lv_obj_create(ui_scrprocessruntimecontainer);
    lv_obj_set_width(ui_scrprocessruntimepanel, 261);
    lv_obj_set_height(ui_scrprocessruntimepanel, 114);
    lv_obj_set_align(ui_scrprocessruntimepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrprocessruntimepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrprocessruntimepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrprocessruntimepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_scrprocessruntimepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_scrprocessruntimepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scrprocessruntimepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrprocessruntimepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_scrprocessruntimepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_scrprocessruntimepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrprocessruntimetitle = lv_label_create(ui_scrprocessruntimecontainer);
    lv_obj_set_width(ui_scrprocessruntimetitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrprocessruntimetitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrprocessruntimetitle, 0);
    lv_obj_set_y(ui_scrprocessruntimetitle, -39);
    lv_obj_set_align(ui_scrprocessruntimetitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrprocessruntimetitle, "Run times");
    lv_obj_set_style_text_color(ui_scrprocessruntimetitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrprocessruntimetitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_scrprocessruntimetitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrprocessruntimetitle, &ui_font_H11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrprocessruntimevalue = lv_label_create(ui_scrprocessruntimecontainer);
    lv_obj_set_width(ui_scrprocessruntimevalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrprocessruntimevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrprocessruntimevalue, 0);
    lv_obj_set_y(ui_scrprocessruntimevalue, 12);
    lv_obj_set_align(ui_scrprocessruntimevalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrprocessruntimevalue, "0s");
    lv_obj_set_style_text_color(ui_scrprocessruntimevalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrprocessruntimevalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrprocessruntimevalue, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrprocessslotssttcontainer = lv_obj_create(ui_scrProcess);
    lv_obj_remove_style_all(ui_scrprocessslotssttcontainer);
    lv_obj_set_width(ui_scrprocessslotssttcontainer, 443);
    lv_obj_set_height(ui_scrprocessslotssttcontainer, 50);
    lv_obj_set_x(ui_scrprocessslotssttcontainer, -175);
    lv_obj_set_y(ui_scrprocessslotssttcontainer, 429);
    lv_obj_set_align(ui_scrprocessslotssttcontainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_scrprocessslotssttcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrprocessslotssttslot1panel = lv_obj_create(ui_scrprocessslotssttcontainer);
    lv_obj_set_width(ui_scrprocessslotssttslot1panel, 20);
    lv_obj_set_height(ui_scrprocessslotssttslot1panel, 20);
    lv_obj_set_x(ui_scrprocessslotssttslot1panel, -196);
    lv_obj_set_y(ui_scrprocessslotssttslot1panel, -12);
    lv_obj_set_align(ui_scrprocessslotssttslot1panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrprocessslotssttslot1panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_shadow_color(ui_scrprocessslotssttslot1panel, lv_color_hex(0x000000),
                                  LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_scrprocessslotssttslot1panel, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_scrprocessslotssttslot2panel = lv_obj_create(ui_scrprocessslotssttcontainer);
    lv_obj_set_width(ui_scrprocessslotssttslot2panel, 20);
    lv_obj_set_height(ui_scrprocessslotssttslot2panel, 20);
    lv_obj_set_x(ui_scrprocessslotssttslot2panel, -166);
    lv_obj_set_y(ui_scrprocessslotssttslot2panel, -12);
    lv_obj_set_align(ui_scrprocessslotssttslot2panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrprocessslotssttslot2panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrprocessslotssttslot3panel = lv_obj_create(ui_scrprocessslotssttcontainer);
    lv_obj_set_width(ui_scrprocessslotssttslot3panel, 20);
    lv_obj_set_height(ui_scrprocessslotssttslot3panel, 20);
    lv_obj_set_x(ui_scrprocessslotssttslot3panel, -136);
    lv_obj_set_y(ui_scrprocessslotssttslot3panel, -12);
    lv_obj_set_align(ui_scrprocessslotssttslot3panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrprocessslotssttslot3panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrprocessslotssttslot4panel = lv_obj_create(ui_scrprocessslotssttcontainer);
    lv_obj_set_width(ui_scrprocessslotssttslot4panel, 20);
    lv_obj_set_height(ui_scrprocessslotssttslot4panel, 20);
    lv_obj_set_x(ui_scrprocessslotssttslot4panel, -106);
    lv_obj_set_y(ui_scrprocessslotssttslot4panel, -12);
    lv_obj_set_align(ui_scrprocessslotssttslot4panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrprocessslotssttslot4panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrprocessslotssttslot5panel = lv_obj_create(ui_scrprocessslotssttcontainer);
    lv_obj_set_width(ui_scrprocessslotssttslot5panel, 20);
    lv_obj_set_height(ui_scrprocessslotssttslot5panel, 20);
    lv_obj_set_x(ui_scrprocessslotssttslot5panel, -76);
    lv_obj_set_y(ui_scrprocessslotssttslot5panel, -12);
    lv_obj_set_align(ui_scrprocessslotssttslot5panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrprocessslotssttslot5panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrprocesschargerimg = lv_img_create(ui_scrProcess);
    lv_img_set_src(ui_scrprocesschargerimg, &ui_img_group_14_png);
    lv_obj_set_width(ui_scrprocesschargerimg, LV_SIZE_CONTENT);   /// 305
    lv_obj_set_height(ui_scrprocesschargerimg, LV_SIZE_CONTENT);    /// 377
    lv_obj_set_x(ui_scrprocesschargerimg, 52);
    lv_obj_set_y(ui_scrprocesschargerimg, 25);
    lv_obj_set_align(ui_scrprocesschargerimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrprocesschargerimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrprocesschargerimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrprocessrobotimg = lv_img_create(ui_scrProcess);
    lv_img_set_src(ui_scrprocessrobotimg, &ui_img_group_13_png);
    lv_obj_set_width(ui_scrprocessrobotimg, LV_SIZE_CONTENT);   /// 216
    lv_obj_set_height(ui_scrprocessrobotimg, LV_SIZE_CONTENT);    /// 387
    lv_obj_set_x(ui_scrprocessrobotimg, 140);
    lv_obj_set_y(ui_scrprocessrobotimg, 10);
    lv_obj_set_align(ui_scrprocessrobotimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrprocessrobotimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrprocessrobotimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_scrprocessrobotimg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrprocessbacktomainbutton = lv_btn_create(ui_scrProcess);
    lv_obj_set_width(ui_scrprocessbacktomainbutton, 231);
    lv_obj_set_height(ui_scrprocessbacktomainbutton, 50);
    lv_obj_set_x(ui_scrprocessbacktomainbutton, 280);
    lv_obj_set_y(ui_scrprocessbacktomainbutton, 214);
    lv_obj_set_align(ui_scrprocessbacktomainbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrprocessbacktomainbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_scrprocessbacktomainbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_scrprocessbacktomainbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrprocessprcontainer = ui_buttoncontainer_create(ui_scrProcess);
    lv_obj_set_x(ui_scrprocessprcontainer, -237);
    lv_obj_set_y(ui_scrprocessprcontainer, -15);

    lv_label_set_text(ui_comp_get_child(ui_scrprocessprcontainer, UI_COMP_BUTTONCONTAINER_BUTONLABEL), "pause");

    ui_scrprocessstopcontainer = ui_buttoncontainer_create(ui_scrProcess);
    lv_obj_set_x(ui_scrprocessstopcontainer, -237);
    lv_obj_set_y(ui_scrprocessstopcontainer, 63);

    lv_label_set_text(ui_comp_get_child(ui_scrprocessstopcontainer, UI_COMP_BUTTONCONTAINER_BUTONLABEL), "stop");

    lv_obj_add_event_cb(ui_scrprocessbacktomainbutton, ui_event_scrprocessbacktomainbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_scrprocessprcontainer, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_scrprocessprcontainer_scrprocessprcontainer_prbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_scrprocessstopcontainer, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_scrprocessstopcontainer_scrprocessstopcontainer_stopbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrProcess, ui_event_scrProcess, LV_EVENT_ALL, NULL);

}

void ui_scrProcess_screen_destroy(void)
{
    if(ui_scrProcess) lv_obj_del(ui_scrProcess);

    // NULL screen variables
    ui_scrProcess = NULL;
    ui_scrprocessstatecontainer = NULL;
    ui_scrprocessstatepanel = NULL;
    ui_scrprocessstatetitlelabel = NULL;
    ui_scrprocessstatevalue = NULL;
    ui_scrprocessvmologo = NULL;
    ui_scrprocessruntimecontainer = NULL;
    ui_scrprocessruntimepanel = NULL;
    ui_scrprocessruntimetitle = NULL;
    ui_scrprocessruntimevalue = NULL;
    ui_scrprocessslotssttcontainer = NULL;
    ui_scrprocessslotssttslot1panel = NULL;
    ui_scrprocessslotssttslot2panel = NULL;
    ui_scrprocessslotssttslot3panel = NULL;
    ui_scrprocessslotssttslot4panel = NULL;
    ui_scrprocessslotssttslot5panel = NULL;
    ui_scrprocesschargerimg = NULL;
    ui_scrprocessrobotimg = NULL;
    ui_scrprocessbacktomainbutton = NULL;
    ui_scrprocessprcontainer = NULL;
    ui_scrprocessstopcontainer = NULL;

}
