// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_scrMain = NULL;
lv_obj_t * ui_imgMainBackground = NULL;
lv_obj_t * ui_lbMainTitle = NULL;
lv_obj_t * ui_ibtMainToSetting = NULL;
lv_obj_t * ui_imgMainSlotSerialDetail1 = NULL;
lv_obj_t * ui_imgMainSlotSerialDetail2 = NULL;
lv_obj_t * ui_imgMainSlotSerialDetail3 = NULL;
lv_obj_t * ui_imgMainSlotSerialDetail4 = NULL;
lv_obj_t * ui_imgMainSlotSerialDetail5 = NULL;
lv_obj_t * ui_btMainSlot1 = NULL;
lv_obj_t * ui_btMainSlot2 = NULL;
lv_obj_t * ui_btMainSlot3 = NULL;
lv_obj_t * ui_btMainSlot4 = NULL;
lv_obj_t * ui_btMainSlot5 = NULL;
lv_obj_t * ui_imgMainEmptyBat1 = NULL;
lv_obj_t * ui_imgMainEmptyBat2 = NULL;
lv_obj_t * ui_imgMainEmptyBat3 = NULL;
lv_obj_t * ui_imgMainEmptyBat4 = NULL;
lv_obj_t * ui_imgMainEmptyBat5 = NULL;
lv_obj_t * ui_barMainBatPercent1 = NULL;
lv_obj_t * ui_barMainBatPercent2 = NULL;
lv_obj_t * ui_barMainBatPercent3 = NULL;
lv_obj_t * ui_barMainBatPercent4 = NULL;
lv_obj_t * ui_barMainBatPercent5 = NULL;
lv_obj_t * ui_imgMainBatWarn1 = NULL;
lv_obj_t * ui_imgMainBatWarn2 = NULL;
lv_obj_t * ui_imgMainBatWarn3 = NULL;
lv_obj_t * ui_imgMainBatWarn4 = NULL;
lv_obj_t * ui_imgMainBatWarn5 = NULL;
lv_obj_t * ui_lbMainSlot1SOC = NULL;
lv_obj_t * ui_lbMainSlot2SOC = NULL;
lv_obj_t * ui_lbMainSlot3SOC = NULL;
lv_obj_t * ui_lbMainSlot4SOC = NULL;
lv_obj_t * ui_lbMainSlot5SOC = NULL;
lv_obj_t * ui_lbMainVoltageSlot1 = NULL;
lv_obj_t * ui_lbMainVoltageSlot2 = NULL;
lv_obj_t * ui_lbMainVoltageSlot3 = NULL;
lv_obj_t * ui_lbMainVoltageSlot4 = NULL;
lv_obj_t * ui_lbMainVoltageSlot5 = NULL;
lv_obj_t * ui_lbMainCapSlot1 = NULL;
lv_obj_t * ui_lbMainCapSlot2 = NULL;
lv_obj_t * ui_lbMainCapSlot3 = NULL;
lv_obj_t * ui_lbMainCapSlot4 = NULL;
lv_obj_t * ui_lbMainCapSlot5 = NULL;
lv_obj_t * ui_imgMainSlotDetalBg = NULL;
lv_obj_t * ui_lbMainSlotBMSState = NULL;
lv_obj_t * ui_lbMainSlotBMSStateValue = NULL;
lv_obj_t * ui_lbMainSlotCtrlRq = NULL;
lv_obj_t * ui_lbMainSlotCtrlRqValue = NULL;
lv_obj_t * ui_lbMainSlotCtrlRp = NULL;
lv_obj_t * ui_lbMainSlotCtrlRpValue = NULL;
lv_obj_t * ui_lbMainSlotFETCtrlP = NULL;
lv_obj_t * ui_lbMainSlotFETCtrlPValue = NULL;
lv_obj_t * ui_lbMainSlotFETStt = NULL;
lv_obj_t * ui_lbMainSlotFETSttValue = NULL;
lv_obj_t * ui_lbMainSlotAlarmBits = NULL;
lv_obj_t * ui_lbMainSlotAlarmBitsValue = NULL;
lv_obj_t * ui_lbMainSlotFault = NULL;
lv_obj_t * ui_lbMainSlotFaultValue = NULL;
lv_obj_t * ui_lbMainSlotPackVolt = NULL;
lv_obj_t * ui_lbMainSlotPackVoltValue = NULL;
lv_obj_t * ui_lbMainSlotStackVolt = NULL;
lv_obj_t * ui_lbMainSlotStackVoltValue = NULL;
lv_obj_t * ui_lbMainSlotPackCur = NULL;
lv_obj_t * ui_lbMainSlotPackCurValue = NULL;
lv_obj_t * ui_lbMainSlotIdVolt = NULL;
lv_obj_t * ui_lbMainSlotIdVoltValue = NULL;
lv_obj_t * ui_lbMainSlotPinPercent = NULL;
lv_obj_t * ui_lbMainSlotPinPercentValue = NULL;
lv_obj_t * ui_lbMainSlotTgPercent = NULL;
lv_obj_t * ui_lbMainSlotTgPercentValue = NULL;
lv_obj_t * ui_lbMainSlotCelRes = NULL;
lv_obj_t * ui_lbMainSlotCelResValue = NULL;
lv_obj_t * ui_lbMainSlotSocPer = NULL;
lv_obj_t * ui_lbMainSlotSocPerValue = NULL;
lv_obj_t * ui_lbMainSlotSOH = NULL;
lv_obj_t * ui_lbMainSlotSOHValue = NULL;
lv_obj_t * ui_lbMainSlotSinPar = NULL;
lv_obj_t * ui_lbMainSlotSinParValue = NULL;
lv_obj_t * ui_lbMainSlotTemp1 = NULL;
lv_obj_t * ui_lbMainSlotTemp1Value = NULL;
lv_obj_t * ui_lbMainSlotTemp2 = NULL;
lv_obj_t * ui_lbMainSlotTemp2Value = NULL;
lv_obj_t * ui_lbMainSlotTemp3 = NULL;
lv_obj_t * ui_lbMainSlotTemp3Value = NULL;
lv_obj_t * ui_lbMainSlotCell1 = NULL;
lv_obj_t * ui_lbMainSlotCell1Value = NULL;
lv_obj_t * ui_lbMainSlotCell2 = NULL;
lv_obj_t * ui_lbMainSlotCell2Value = NULL;
lv_obj_t * ui_lbMainSlotCell3 = NULL;
lv_obj_t * ui_lbMainSlotCell3Value = NULL;
lv_obj_t * ui_lbMainSlotCell4 = NULL;
lv_obj_t * ui_lbMainSlotCell4Value = NULL;
lv_obj_t * ui_lbMainSlotCell5 = NULL;
lv_obj_t * ui_lbMainSlotCell5Value = NULL;
lv_obj_t * ui_lbMainSlotCell6 = NULL;
lv_obj_t * ui_lbMainSlotCell6Value = NULL;
lv_obj_t * ui_lbMainSlotCell7 = NULL;
lv_obj_t * ui_lbMainSlotCell7Value = NULL;
lv_obj_t * ui_lbMainSlotCell8 = NULL;
lv_obj_t * ui_lbMainSlotCell8Value = NULL;
lv_obj_t * ui_lbMainSlotCell9 = NULL;
lv_obj_t * ui_lbMainSlotCell9Value = NULL;
lv_obj_t * ui_lbMainSlotCell10 = NULL;
lv_obj_t * ui_lbMainSlotCell10Value = NULL;
lv_obj_t * ui_lbMainSlotCell11 = NULL;
lv_obj_t * ui_lbMainSlotCell11Value = NULL;
lv_obj_t * ui_lbMainSlotCell12 = NULL;
lv_obj_t * ui_lbMainSlotCell12Value = NULL;
lv_obj_t * ui_lbMainSlotCell13 = NULL;
lv_obj_t * ui_lbMainSlotCell13Value = NULL;
lv_obj_t * ui_lbMainSlotACCUInt = NULL;
lv_obj_t * ui_lbMainSlotACCUIntValue = NULL;
lv_obj_t * ui_lbMainSlotACCUFrac = NULL;
lv_obj_t * ui_lbMainSlotACCUFracValue = NULL;
lv_obj_t * ui_lbMainSlotACCUTime = NULL;
lv_obj_t * ui_lbMainSlotACCUTimeValue = NULL;
lv_obj_t * ui_lbMainSlotSafetyA = NULL;
lv_obj_t * ui_lbMainSlotSafetyAValue = NULL;
lv_obj_t * ui_lbMainSlotSafetyB = NULL;
lv_obj_t * ui_lbMainSlotSafetyBValue = NULL;
lv_obj_t * ui_lbMainSlotSafetyC = NULL;
lv_obj_t * ui_lbMainSlotSafetyCValue = NULL;
lv_obj_t * ui_ibtMainManualSwap = NULL;
lv_obj_t * ui_imgMainBotbotEmptyPin = NULL;
lv_obj_t * ui_imgMainRobotFullPin = NULL;
lv_obj_t * ui_imgMainRobotCharging = NULL;
lv_obj_t * ui_imgMainRbToSlot1 = NULL;
lv_obj_t * ui_imgMainRbToSlot2 = NULL;
lv_obj_t * ui_imgMainRbToSlot3 = NULL;
lv_obj_t * ui_imgMainRbToSlot4 = NULL;
lv_obj_t * ui_imgMainRbToSlot5 = NULL;
lv_obj_t * ui_imgMainBattery = NULL;
lv_obj_t * ui_imgMainNotConnect = NULL;
// event funtions
void ui_event_ibtMainToSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fnMainChangeSettingClicked(e);
    }
}

// build funtions

void ui_scrMain_screen_init(void)
{
    ui_scrMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrMain, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgMainBackground = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainBackground, &ui_img_imgmainbackground_png);
    lv_obj_set_width(ui_imgMainBackground, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_imgMainBackground, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_imgMainBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainBackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbMainTitle = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainTitle, 0);
    lv_obj_set_y(ui_lbMainTitle, -215);
    lv_obj_set_align(ui_lbMainTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainTitle, "BATTERY HOT SWAP STATION");
    lv_obj_set_style_text_color(ui_lbMainTitle, lv_color_hex(0x314C83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbMainTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lbMainTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_lbMainTitle, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbMainTitle, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ibtMainToSetting = lv_imgbtn_create(ui_scrMain);
    lv_imgbtn_set_src(ui_ibtMainToSetting, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_scrsettingicon_png, NULL);
    lv_obj_set_width(ui_ibtMainToSetting, 50);
    lv_obj_set_height(ui_ibtMainToSetting, 50);
    lv_obj_set_x(ui_ibtMainToSetting, 372);
    lv_obj_set_y(ui_ibtMainToSetting, -212);
    lv_obj_set_align(ui_ibtMainToSetting, LV_ALIGN_CENTER);

    ui_imgMainSlotSerialDetail1 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainSlotSerialDetail1, &ui_img_imgmainslotserialdetail_png);
    lv_obj_set_width(ui_imgMainSlotSerialDetail1, LV_SIZE_CONTENT);   /// 9
    lv_obj_set_height(ui_imgMainSlotSerialDetail1, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_imgMainSlotSerialDetail1, -138);
    lv_obj_set_y(ui_imgMainSlotSerialDetail1, -145);
    lv_obj_set_align(ui_imgMainSlotSerialDetail1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainSlotSerialDetail1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainSlotSerialDetail1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainSlotSerialDetail2 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainSlotSerialDetail2, &ui_img_imgmainslotserialdetail_png);
    lv_obj_set_width(ui_imgMainSlotSerialDetail2, LV_SIZE_CONTENT);   /// 9
    lv_obj_set_height(ui_imgMainSlotSerialDetail2, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_imgMainSlotSerialDetail2, -138);
    lv_obj_set_y(ui_imgMainSlotSerialDetail2, -60);
    lv_obj_set_align(ui_imgMainSlotSerialDetail2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainSlotSerialDetail2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainSlotSerialDetail2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainSlotSerialDetail3 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainSlotSerialDetail3, &ui_img_imgmainslotserialdetail_png);
    lv_obj_set_width(ui_imgMainSlotSerialDetail3, LV_SIZE_CONTENT);   /// 9
    lv_obj_set_height(ui_imgMainSlotSerialDetail3, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_imgMainSlotSerialDetail3, -138);
    lv_obj_set_y(ui_imgMainSlotSerialDetail3, 25);
    lv_obj_set_align(ui_imgMainSlotSerialDetail3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainSlotSerialDetail3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainSlotSerialDetail3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainSlotSerialDetail4 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainSlotSerialDetail4, &ui_img_imgmainslotserialdetail_png);
    lv_obj_set_width(ui_imgMainSlotSerialDetail4, LV_SIZE_CONTENT);   /// 9
    lv_obj_set_height(ui_imgMainSlotSerialDetail4, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_imgMainSlotSerialDetail4, -138);
    lv_obj_set_y(ui_imgMainSlotSerialDetail4, 110);
    lv_obj_set_align(ui_imgMainSlotSerialDetail4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainSlotSerialDetail4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainSlotSerialDetail4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainSlotSerialDetail5 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainSlotSerialDetail5, &ui_img_imgmainslotserialdetail_png);
    lv_obj_set_width(ui_imgMainSlotSerialDetail5, LV_SIZE_CONTENT);   /// 9
    lv_obj_set_height(ui_imgMainSlotSerialDetail5, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_imgMainSlotSerialDetail5, -138);
    lv_obj_set_y(ui_imgMainSlotSerialDetail5, 195);
    lv_obj_set_align(ui_imgMainSlotSerialDetail5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainSlotSerialDetail5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainSlotSerialDetail5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btMainSlot1 = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_btMainSlot1, 250);
    lv_obj_set_height(ui_btMainSlot1, 75);
    lv_obj_set_x(ui_btMainSlot1, -267);
    lv_obj_set_y(ui_btMainSlot1, -145);
    lv_obj_set_align(ui_btMainSlot1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btMainSlot1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btMainSlot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btMainSlot1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btMainSlot1, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btMainSlot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btMainSlot1, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btMainSlot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btMainSlot2 = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_btMainSlot2, 250);
    lv_obj_set_height(ui_btMainSlot2, 75);
    lv_obj_set_x(ui_btMainSlot2, -267);
    lv_obj_set_y(ui_btMainSlot2, -60);
    lv_obj_set_align(ui_btMainSlot2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btMainSlot2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btMainSlot2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btMainSlot2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btMainSlot2, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btMainSlot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btMainSlot2, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btMainSlot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btMainSlot3 = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_btMainSlot3, 250);
    lv_obj_set_height(ui_btMainSlot3, 75);
    lv_obj_set_x(ui_btMainSlot3, -267);
    lv_obj_set_y(ui_btMainSlot3, 25);
    lv_obj_set_align(ui_btMainSlot3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btMainSlot3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btMainSlot3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btMainSlot3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btMainSlot3, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btMainSlot3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btMainSlot3, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btMainSlot3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btMainSlot4 = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_btMainSlot4, 250);
    lv_obj_set_height(ui_btMainSlot4, 75);
    lv_obj_set_x(ui_btMainSlot4, -267);
    lv_obj_set_y(ui_btMainSlot4, 110);
    lv_obj_set_align(ui_btMainSlot4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btMainSlot4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btMainSlot4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btMainSlot4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btMainSlot4, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btMainSlot4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btMainSlot4, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btMainSlot4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btMainSlot5 = lv_btn_create(ui_scrMain);
    lv_obj_set_width(ui_btMainSlot5, 250);
    lv_obj_set_height(ui_btMainSlot5, 75);
    lv_obj_set_x(ui_btMainSlot5, -267);
    lv_obj_set_y(ui_btMainSlot5, 195);
    lv_obj_set_align(ui_btMainSlot5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btMainSlot5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btMainSlot5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btMainSlot5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btMainSlot5, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btMainSlot5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btMainSlot5, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btMainSlot5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgMainEmptyBat1 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainEmptyBat1, &ui_img_scrmain_batteryempty_png);
    lv_obj_set_width(ui_imgMainEmptyBat1, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_imgMainEmptyBat1, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_imgMainEmptyBat1, -347);
    lv_obj_set_y(ui_imgMainEmptyBat1, -160);
    lv_obj_set_align(ui_imgMainEmptyBat1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainEmptyBat1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainEmptyBat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainEmptyBat2 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainEmptyBat2, &ui_img_scrmain_batteryempty_png);
    lv_obj_set_width(ui_imgMainEmptyBat2, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_imgMainEmptyBat2, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_imgMainEmptyBat2, -347);
    lv_obj_set_y(ui_imgMainEmptyBat2, -75);
    lv_obj_set_align(ui_imgMainEmptyBat2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainEmptyBat2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainEmptyBat2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainEmptyBat3 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainEmptyBat3, &ui_img_scrmain_batteryempty_png);
    lv_obj_set_width(ui_imgMainEmptyBat3, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_imgMainEmptyBat3, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_imgMainEmptyBat3, -347);
    lv_obj_set_y(ui_imgMainEmptyBat3, 10);
    lv_obj_set_align(ui_imgMainEmptyBat3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainEmptyBat3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainEmptyBat3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainEmptyBat4 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainEmptyBat4, &ui_img_scrmain_batteryempty_png);
    lv_obj_set_width(ui_imgMainEmptyBat4, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_imgMainEmptyBat4, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_imgMainEmptyBat4, -347);
    lv_obj_set_y(ui_imgMainEmptyBat4, 95);
    lv_obj_set_align(ui_imgMainEmptyBat4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainEmptyBat4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainEmptyBat4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainEmptyBat5 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainEmptyBat5, &ui_img_scrmain_batteryempty_png);
    lv_obj_set_width(ui_imgMainEmptyBat5, LV_SIZE_CONTENT);   /// 59
    lv_obj_set_height(ui_imgMainEmptyBat5, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_imgMainEmptyBat5, -347);
    lv_obj_set_y(ui_imgMainEmptyBat5, 180);
    lv_obj_set_align(ui_imgMainEmptyBat5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainEmptyBat5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainEmptyBat5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_barMainBatPercent1 = lv_bar_create(ui_scrMain);
    lv_bar_set_value(ui_barMainBatPercent1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barMainBatPercent1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barMainBatPercent1, 45);
    lv_obj_set_height(ui_barMainBatPercent1, 21);
    lv_obj_set_x(ui_barMainBatPercent1, -349);
    lv_obj_set_y(ui_barMainBatPercent1, -160);
    lv_obj_set_align(ui_barMainBatPercent1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_barMainBatPercent1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_barMainBatPercent1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barMainBatPercent1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barMainBatPercent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barMainBatPercent1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barMainBatPercent1, lv_color_hex(0x0D0C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barMainBatPercent1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_barMainBatPercent2 = lv_bar_create(ui_scrMain);
    lv_bar_set_value(ui_barMainBatPercent2, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barMainBatPercent2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barMainBatPercent2, 45);
    lv_obj_set_height(ui_barMainBatPercent2, 21);
    lv_obj_set_x(ui_barMainBatPercent2, -349);
    lv_obj_set_y(ui_barMainBatPercent2, -75);
    lv_obj_set_align(ui_barMainBatPercent2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_barMainBatPercent2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_barMainBatPercent2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barMainBatPercent2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barMainBatPercent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barMainBatPercent2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barMainBatPercent2, lv_color_hex(0x0D0C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barMainBatPercent2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_barMainBatPercent3 = lv_bar_create(ui_scrMain);
    lv_bar_set_value(ui_barMainBatPercent3, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barMainBatPercent3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barMainBatPercent3, 45);
    lv_obj_set_height(ui_barMainBatPercent3, 21);
    lv_obj_set_x(ui_barMainBatPercent3, -349);
    lv_obj_set_y(ui_barMainBatPercent3, 10);
    lv_obj_set_align(ui_barMainBatPercent3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_barMainBatPercent3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_barMainBatPercent3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barMainBatPercent3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barMainBatPercent3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barMainBatPercent3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barMainBatPercent3, lv_color_hex(0x0D0C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barMainBatPercent3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_barMainBatPercent4 = lv_bar_create(ui_scrMain);
    lv_bar_set_value(ui_barMainBatPercent4, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barMainBatPercent4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barMainBatPercent4, 45);
    lv_obj_set_height(ui_barMainBatPercent4, 21);
    lv_obj_set_x(ui_barMainBatPercent4, -349);
    lv_obj_set_y(ui_barMainBatPercent4, 95);
    lv_obj_set_align(ui_barMainBatPercent4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_barMainBatPercent4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_barMainBatPercent4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barMainBatPercent4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barMainBatPercent4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barMainBatPercent4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barMainBatPercent4, lv_color_hex(0x0D0C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barMainBatPercent4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_barMainBatPercent5 = lv_bar_create(ui_scrMain);
    lv_bar_set_value(ui_barMainBatPercent5, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barMainBatPercent5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barMainBatPercent5, 45);
    lv_obj_set_height(ui_barMainBatPercent5, 21);
    lv_obj_set_x(ui_barMainBatPercent5, -349);
    lv_obj_set_y(ui_barMainBatPercent5, 180);
    lv_obj_set_align(ui_barMainBatPercent5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_barMainBatPercent5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_barMainBatPercent5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barMainBatPercent5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barMainBatPercent5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barMainBatPercent5, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barMainBatPercent5, lv_color_hex(0x0D0C0C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barMainBatPercent5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_imgMainBatWarn1 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainBatWarn1, &ui_img_scrmain_batterywarning_png);
    lv_obj_set_width(ui_imgMainBatWarn1, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_imgMainBatWarn1, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_imgMainBatWarn1, -350);
    lv_obj_set_y(ui_imgMainBatWarn1, -160);
    lv_obj_set_align(ui_imgMainBatWarn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainBatWarn1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainBatWarn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainBatWarn2 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainBatWarn2, &ui_img_scrmain_batterywarning_png);
    lv_obj_set_width(ui_imgMainBatWarn2, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_imgMainBatWarn2, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_imgMainBatWarn2, -350);
    lv_obj_set_y(ui_imgMainBatWarn2, -75);
    lv_obj_set_align(ui_imgMainBatWarn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainBatWarn2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainBatWarn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainBatWarn3 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainBatWarn3, &ui_img_scrmain_batterywarning_png);
    lv_obj_set_width(ui_imgMainBatWarn3, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_imgMainBatWarn3, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_imgMainBatWarn3, -350);
    lv_obj_set_y(ui_imgMainBatWarn3, 10);
    lv_obj_set_align(ui_imgMainBatWarn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainBatWarn3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainBatWarn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainBatWarn4 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainBatWarn4, &ui_img_scrmain_batterywarning_png);
    lv_obj_set_width(ui_imgMainBatWarn4, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_imgMainBatWarn4, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_imgMainBatWarn4, -350);
    lv_obj_set_y(ui_imgMainBatWarn4, 95);
    lv_obj_set_align(ui_imgMainBatWarn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainBatWarn4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainBatWarn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainBatWarn5 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainBatWarn5, &ui_img_scrmain_batterywarning_png);
    lv_obj_set_width(ui_imgMainBatWarn5, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_imgMainBatWarn5, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_imgMainBatWarn5, -350);
    lv_obj_set_y(ui_imgMainBatWarn5, 180);
    lv_obj_set_align(ui_imgMainBatWarn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainBatWarn5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainBatWarn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbMainSlot1SOC = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainSlot1SOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlot1SOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlot1SOC, -345);
    lv_obj_set_y(ui_lbMainSlot1SOC, -125);
    lv_obj_set_align(ui_lbMainSlot1SOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlot1SOC, "34%");
    lv_obj_add_flag(ui_lbMainSlot1SOC, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainSlot1SOC, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlot2SOC = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainSlot2SOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlot2SOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlot2SOC, -345);
    lv_obj_set_y(ui_lbMainSlot2SOC, -40);
    lv_obj_set_align(ui_lbMainSlot2SOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlot2SOC, "34%");
    lv_obj_add_flag(ui_lbMainSlot2SOC, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainSlot2SOC, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlot3SOC = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainSlot3SOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlot3SOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlot3SOC, -347);
    lv_obj_set_y(ui_lbMainSlot3SOC, 45);
    lv_obj_set_align(ui_lbMainSlot3SOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlot3SOC, "34%");
    lv_obj_add_flag(ui_lbMainSlot3SOC, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainSlot3SOC, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlot4SOC = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainSlot4SOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlot4SOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlot4SOC, -347);
    lv_obj_set_y(ui_lbMainSlot4SOC, 130);
    lv_obj_set_align(ui_lbMainSlot4SOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlot4SOC, "34%");
    lv_obj_add_flag(ui_lbMainSlot4SOC, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainSlot4SOC, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlot5SOC = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainSlot5SOC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlot5SOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlot5SOC, -347);
    lv_obj_set_y(ui_lbMainSlot5SOC, 215);
    lv_obj_set_align(ui_lbMainSlot5SOC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlot5SOC, "34%");
    lv_obj_add_flag(ui_lbMainSlot5SOC, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainSlot5SOC, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainVoltageSlot1 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainVoltageSlot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainVoltageSlot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainVoltageSlot1, -223);
    lv_obj_set_y(ui_lbMainVoltageSlot1, -160);
    lv_obj_set_align(ui_lbMainVoltageSlot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainVoltageSlot1, "42.5V");
    lv_obj_add_flag(ui_lbMainVoltageSlot1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainVoltageSlot1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainVoltageSlot2 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainVoltageSlot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainVoltageSlot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainVoltageSlot2, -223);
    lv_obj_set_y(ui_lbMainVoltageSlot2, -75);
    lv_obj_set_align(ui_lbMainVoltageSlot2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainVoltageSlot2, "42.5V");
    lv_obj_add_flag(ui_lbMainVoltageSlot2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainVoltageSlot2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainVoltageSlot3 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainVoltageSlot3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainVoltageSlot3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainVoltageSlot3, -223);
    lv_obj_set_y(ui_lbMainVoltageSlot3, 10);
    lv_obj_set_align(ui_lbMainVoltageSlot3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainVoltageSlot3, "42.5V");
    lv_obj_add_flag(ui_lbMainVoltageSlot3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainVoltageSlot3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainVoltageSlot4 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainVoltageSlot4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainVoltageSlot4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainVoltageSlot4, -223);
    lv_obj_set_y(ui_lbMainVoltageSlot4, 95);
    lv_obj_set_align(ui_lbMainVoltageSlot4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainVoltageSlot4, "42.5V");
    lv_obj_add_flag(ui_lbMainVoltageSlot4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainVoltageSlot4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainVoltageSlot5 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainVoltageSlot5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainVoltageSlot5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainVoltageSlot5, -223);
    lv_obj_set_y(ui_lbMainVoltageSlot5, 180);
    lv_obj_set_align(ui_lbMainVoltageSlot5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainVoltageSlot5, "42.5V");
    lv_obj_add_flag(ui_lbMainVoltageSlot5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainVoltageSlot5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainCapSlot1 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainCapSlot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainCapSlot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainCapSlot1, -223);
    lv_obj_set_y(ui_lbMainCapSlot1, -130);
    lv_obj_set_align(ui_lbMainCapSlot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainCapSlot1, "3700mAh");
    lv_obj_add_flag(ui_lbMainCapSlot1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainCapSlot1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainCapSlot2 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainCapSlot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainCapSlot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainCapSlot2, -223);
    lv_obj_set_y(ui_lbMainCapSlot2, -45);
    lv_obj_set_align(ui_lbMainCapSlot2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainCapSlot2, "3700mAh");
    lv_obj_add_flag(ui_lbMainCapSlot2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainCapSlot2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainCapSlot3 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainCapSlot3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainCapSlot3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainCapSlot3, -223);
    lv_obj_set_y(ui_lbMainCapSlot3, 40);
    lv_obj_set_align(ui_lbMainCapSlot3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainCapSlot3, "3700mAh");
    lv_obj_add_flag(ui_lbMainCapSlot3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainCapSlot3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainCapSlot4 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainCapSlot4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainCapSlot4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainCapSlot4, -223);
    lv_obj_set_y(ui_lbMainCapSlot4, 125);
    lv_obj_set_align(ui_lbMainCapSlot4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainCapSlot4, "3700mAh");
    lv_obj_add_flag(ui_lbMainCapSlot4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainCapSlot4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainCapSlot5 = lv_label_create(ui_scrMain);
    lv_obj_set_width(ui_lbMainCapSlot5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainCapSlot5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainCapSlot5, -223);
    lv_obj_set_y(ui_lbMainCapSlot5, 210);
    lv_obj_set_align(ui_lbMainCapSlot5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainCapSlot5, "3700mAh");
    lv_obj_add_flag(ui_lbMainCapSlot5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_lbMainCapSlot5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgMainSlotDetalBg = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainSlotDetalBg, &ui_img_imgmainslotdetailbackground_png);
    lv_obj_set_width(ui_imgMainSlotDetalBg, LV_SIZE_CONTENT);   /// 523
    lv_obj_set_height(ui_imgMainSlotDetalBg, LV_SIZE_CONTENT);    /// 415
    lv_obj_set_x(ui_imgMainSlotDetalBg, 129);
    lv_obj_set_y(ui_imgMainSlotDetalBg, 25);
    lv_obj_set_align(ui_imgMainSlotDetalBg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainSlotDetalBg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainSlotDetalBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imgMainSlotDetalBg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imgMainSlotDetalBg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotBMSState = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotBMSState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotBMSState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotBMSState, -160);
    lv_obj_set_y(ui_lbMainSlotBMSState, -190);
    lv_obj_set_align(ui_lbMainSlotBMSState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotBMSState, "BMS State: ");
    lv_obj_set_style_text_font(ui_lbMainSlotBMSState, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotBMSStateValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotBMSStateValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotBMSStateValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotBMSStateValue, -70);
    lv_obj_set_y(ui_lbMainSlotBMSStateValue, -190);
    lv_obj_set_align(ui_lbMainSlotBMSStateValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotBMSStateValue, "STANDBY");
    lv_obj_set_style_text_font(ui_lbMainSlotBMSStateValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCtrlRq = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCtrlRq, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCtrlRq, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCtrlRq, -148);
    lv_obj_set_y(ui_lbMainSlotCtrlRq, -170);
    lv_obj_set_align(ui_lbMainSlotCtrlRq, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCtrlRq, "Ctrl Rq:");
    lv_obj_set_style_text_font(ui_lbMainSlotCtrlRq, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCtrlRqValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCtrlRqValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCtrlRqValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCtrlRqValue, -70);
    lv_obj_set_y(ui_lbMainSlotCtrlRqValue, -170);
    lv_obj_set_align(ui_lbMainSlotCtrlRqValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCtrlRqValue, "0");
    lv_obj_set_style_text_font(ui_lbMainSlotCtrlRqValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCtrlRp = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCtrlRp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCtrlRp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCtrlRp, -148);
    lv_obj_set_y(ui_lbMainSlotCtrlRp, -150);
    lv_obj_set_align(ui_lbMainSlotCtrlRp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCtrlRp, "Ctrl Rp:");
    lv_obj_set_style_text_font(ui_lbMainSlotCtrlRp, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCtrlRpValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCtrlRpValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCtrlRpValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCtrlRpValue, -70);
    lv_obj_set_y(ui_lbMainSlotCtrlRpValue, -150);
    lv_obj_set_align(ui_lbMainSlotCtrlRpValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCtrlRpValue, "0");
    lv_obj_set_style_text_font(ui_lbMainSlotCtrlRpValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotFETCtrlP = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotFETCtrlP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotFETCtrlP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotFETCtrlP, -167);
    lv_obj_set_y(ui_lbMainSlotFETCtrlP, -130);
    lv_obj_set_align(ui_lbMainSlotFETCtrlP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotFETCtrlP, "FET Ctrl Pin:");
    lv_obj_set_style_text_font(ui_lbMainSlotFETCtrlP, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotFETCtrlPValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotFETCtrlPValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotFETCtrlPValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotFETCtrlPValue, -70);
    lv_obj_set_y(ui_lbMainSlotFETCtrlPValue, -130);
    lv_obj_set_align(ui_lbMainSlotFETCtrlPValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotFETCtrlPValue, "3");
    lv_obj_set_style_text_font(ui_lbMainSlotFETCtrlPValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotFETStt = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotFETStt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotFETStt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotFETStt, -164);
    lv_obj_set_y(ui_lbMainSlotFETStt, -110);
    lv_obj_set_align(ui_lbMainSlotFETStt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotFETStt, "FET Status:");
    lv_obj_set_style_text_font(ui_lbMainSlotFETStt, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotFETSttValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotFETSttValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotFETSttValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotFETSttValue, -70);
    lv_obj_set_y(ui_lbMainSlotFETSttValue, -110);
    lv_obj_set_align(ui_lbMainSlotFETSttValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotFETSttValue, "CHG");
    lv_obj_set_style_text_font(ui_lbMainSlotFETSttValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotAlarmBits = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotAlarmBits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotAlarmBits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotAlarmBits, -162);
    lv_obj_set_y(ui_lbMainSlotAlarmBits, -90);
    lv_obj_set_align(ui_lbMainSlotAlarmBits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotAlarmBits, "Alarm Bits:");
    lv_obj_set_style_text_font(ui_lbMainSlotAlarmBits, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotAlarmBitsValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotAlarmBitsValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotAlarmBitsValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotAlarmBitsValue, -70);
    lv_obj_set_y(ui_lbMainSlotAlarmBitsValue, -90);
    lv_obj_set_align(ui_lbMainSlotAlarmBitsValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotAlarmBitsValue, "130");
    lv_obj_set_style_text_font(ui_lbMainSlotAlarmBitsValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotFault = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotFault, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotFault, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotFault, -142);
    lv_obj_set_y(ui_lbMainSlotFault, -70);
    lv_obj_set_align(ui_lbMainSlotFault, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotFault, "Fault:");
    lv_obj_set_style_text_font(ui_lbMainSlotFault, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotFaultValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotFaultValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotFaultValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotFaultValue, -70);
    lv_obj_set_y(ui_lbMainSlotFaultValue, -70);
    lv_obj_set_align(ui_lbMainSlotFaultValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotFaultValue, "NONE");
    lv_obj_set_style_text_font(ui_lbMainSlotFaultValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotPackVolt = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotPackVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotPackVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotPackVolt, -159);
    lv_obj_set_y(ui_lbMainSlotPackVolt, -50);
    lv_obj_set_align(ui_lbMainSlotPackVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotPackVolt, "Pack Volt:");
    lv_obj_set_style_text_font(ui_lbMainSlotPackVolt, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotPackVoltValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotPackVoltValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotPackVoltValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotPackVoltValue, -70);
    lv_obj_set_y(ui_lbMainSlotPackVoltValue, -50);
    lv_obj_set_align(ui_lbMainSlotPackVoltValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotPackVoltValue, "1.26V");
    lv_obj_set_style_text_font(ui_lbMainSlotPackVoltValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotStackVolt = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotStackVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotStackVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotStackVolt, -162);
    lv_obj_set_y(ui_lbMainSlotStackVolt, -30);
    lv_obj_set_align(ui_lbMainSlotStackVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotStackVolt, "Stack Volt:");
    lv_obj_set_style_text_font(ui_lbMainSlotStackVolt, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotStackVoltValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotStackVoltValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotStackVoltValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotStackVoltValue, -70);
    lv_obj_set_y(ui_lbMainSlotStackVoltValue, -30);
    lv_obj_set_align(ui_lbMainSlotStackVoltValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotStackVoltValue, "54.12V");
    lv_obj_set_style_text_font(ui_lbMainSlotStackVoltValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotPackCur = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotPackCur, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotPackCur, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotPackCur, -157);
    lv_obj_set_y(ui_lbMainSlotPackCur, -10);
    lv_obj_set_align(ui_lbMainSlotPackCur, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotPackCur, "Pack Cur:");
    lv_obj_set_style_text_font(ui_lbMainSlotPackCur, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotPackCurValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotPackCurValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotPackCurValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotPackCurValue, -70);
    lv_obj_set_y(ui_lbMainSlotPackCurValue, -10);
    lv_obj_set_align(ui_lbMainSlotPackCurValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotPackCurValue, "0.0A");
    lv_obj_set_style_text_font(ui_lbMainSlotPackCurValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotIdVolt = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotIdVolt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotIdVolt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotIdVolt, -147);
    lv_obj_set_y(ui_lbMainSlotIdVolt, 10);
    lv_obj_set_align(ui_lbMainSlotIdVolt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotIdVolt, "Id Volt:");
    lv_obj_set_style_text_font(ui_lbMainSlotIdVolt, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotIdVoltValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotIdVoltValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotIdVoltValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotIdVoltValue, -70);
    lv_obj_set_y(ui_lbMainSlotIdVoltValue, 10);
    lv_obj_set_align(ui_lbMainSlotIdVoltValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotIdVoltValue, "2.85A");
    lv_obj_set_style_text_font(ui_lbMainSlotIdVoltValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotPinPercent = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotPinPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotPinPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotPinPercent, -167);
    lv_obj_set_y(ui_lbMainSlotPinPercent, 30);
    lv_obj_set_align(ui_lbMainSlotPinPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotPinPercent, "Pin Percent:");
    lv_obj_set_style_text_font(ui_lbMainSlotPinPercent, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotPinPercentValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotPinPercentValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotPinPercentValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotPinPercentValue, -70);
    lv_obj_set_y(ui_lbMainSlotPinPercentValue, 30);
    lv_obj_set_align(ui_lbMainSlotPinPercentValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotPinPercentValue, "100%");
    lv_obj_set_style_text_font(ui_lbMainSlotPinPercentValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotTgPercent = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotTgPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotTgPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotTgPercent, -164);
    lv_obj_set_y(ui_lbMainSlotTgPercent, 50);
    lv_obj_set_align(ui_lbMainSlotTgPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotTgPercent, "Tg Percent:");
    lv_obj_set_style_text_font(ui_lbMainSlotTgPercent, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotTgPercentValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotTgPercentValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotTgPercentValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotTgPercentValue, -70);
    lv_obj_set_y(ui_lbMainSlotTgPercentValue, 50);
    lv_obj_set_align(ui_lbMainSlotTgPercentValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotTgPercentValue, "100%");
    lv_obj_set_style_text_font(ui_lbMainSlotTgPercentValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCelRes = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCelRes, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCelRes, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCelRes, -152);
    lv_obj_set_y(ui_lbMainSlotCelRes, 70);
    lv_obj_set_align(ui_lbMainSlotCelRes, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCelRes, "Cell Res:");
    lv_obj_set_style_text_font(ui_lbMainSlotCelRes, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCelResValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCelResValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCelResValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCelResValue, -70);
    lv_obj_set_y(ui_lbMainSlotCelResValue, 70);
    lv_obj_set_align(ui_lbMainSlotCelResValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCelResValue, "12R");
    lv_obj_set_style_text_font(ui_lbMainSlotCelResValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSocPer = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSocPer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSocPer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSocPer, -172);
    lv_obj_set_y(ui_lbMainSlotSocPer, 90);
    lv_obj_set_align(ui_lbMainSlotSocPer, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSocPer, "SOC Percent:");
    lv_obj_set_style_text_font(ui_lbMainSlotSocPer, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSocPerValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSocPerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSocPerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSocPerValue, -70);
    lv_obj_set_y(ui_lbMainSlotSocPerValue, 90);
    lv_obj_set_align(ui_lbMainSlotSocPerValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSocPerValue, "100%");
    lv_obj_set_style_text_font(ui_lbMainSlotSocPerValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSOH = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSOH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSOH, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSOH, -138);
    lv_obj_set_y(ui_lbMainSlotSOH, 110);
    lv_obj_set_align(ui_lbMainSlotSOH, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSOH, "SOH:");
    lv_obj_set_style_text_font(ui_lbMainSlotSOH, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSOHValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSOHValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSOHValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSOHValue, -70);
    lv_obj_set_y(ui_lbMainSlotSOHValue, 110);
    lv_obj_set_align(ui_lbMainSlotSOHValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSOHValue, "3700");
    lv_obj_set_style_text_font(ui_lbMainSlotSOHValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSinPar = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSinPar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSinPar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSinPar, -178);
    lv_obj_set_y(ui_lbMainSlotSinPar, 130);
    lv_obj_set_align(ui_lbMainSlotSinPar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSinPar, "Single/Parallel:");
    lv_obj_set_style_text_font(ui_lbMainSlotSinPar, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSinParValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSinParValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSinParValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSinParValue, -70);
    lv_obj_set_y(ui_lbMainSlotSinParValue, 130);
    lv_obj_set_align(ui_lbMainSlotSinParValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSinParValue, "0");
    lv_obj_set_style_text_font(ui_lbMainSlotSinParValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotTemp1 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotTemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotTemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotTemp1, -149);
    lv_obj_set_y(ui_lbMainSlotTemp1, 150);
    lv_obj_set_align(ui_lbMainSlotTemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotTemp1, "Temp 1:");
    lv_obj_set_style_text_font(ui_lbMainSlotTemp1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotTemp1Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotTemp1Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotTemp1Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotTemp1Value, -70);
    lv_obj_set_y(ui_lbMainSlotTemp1Value, 150);
    lv_obj_set_align(ui_lbMainSlotTemp1Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotTemp1Value, "16854");
    lv_obj_set_style_text_font(ui_lbMainSlotTemp1Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotTemp2 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotTemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotTemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotTemp2, -149);
    lv_obj_set_y(ui_lbMainSlotTemp2, 170);
    lv_obj_set_align(ui_lbMainSlotTemp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotTemp2, "Temp 2:");
    lv_obj_set_style_text_font(ui_lbMainSlotTemp2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotTemp2Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotTemp2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotTemp2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotTemp2Value, -70);
    lv_obj_set_y(ui_lbMainSlotTemp2Value, 170);
    lv_obj_set_align(ui_lbMainSlotTemp2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotTemp2Value, "32143");
    lv_obj_set_style_text_font(ui_lbMainSlotTemp2Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotTemp3 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotTemp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotTemp3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotTemp3, -149);
    lv_obj_set_y(ui_lbMainSlotTemp3, 190);
    lv_obj_set_align(ui_lbMainSlotTemp3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotTemp3, "Temp 3:");
    lv_obj_set_style_text_font(ui_lbMainSlotTemp3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotTemp3Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotTemp3Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotTemp3Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotTemp3Value, -70);
    lv_obj_set_y(ui_lbMainSlotTemp3Value, 190);
    lv_obj_set_align(ui_lbMainSlotTemp3Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotTemp3Value, "43242");
    lv_obj_set_style_text_font(ui_lbMainSlotTemp3Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell1 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell1, 70);
    lv_obj_set_y(ui_lbMainSlotCell1, -190);
    lv_obj_set_align(ui_lbMainSlotCell1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell1, "Cell 1:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell1Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell1Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell1Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell1Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell1Value, -190);
    lv_obj_set_align(ui_lbMainSlotCell1Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell1Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell1Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell2 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell2, 70);
    lv_obj_set_y(ui_lbMainSlotCell2, -170);
    lv_obj_set_align(ui_lbMainSlotCell2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell2, "Cell 2:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell2Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell2Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell2Value, -170);
    lv_obj_set_align(ui_lbMainSlotCell2Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell2Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell2Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell3 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell3, 70);
    lv_obj_set_y(ui_lbMainSlotCell3, -150);
    lv_obj_set_align(ui_lbMainSlotCell3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell3, "Cell 3:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell3Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell3Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell3Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell3Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell3Value, -150);
    lv_obj_set_align(ui_lbMainSlotCell3Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell3Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell3Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell4 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell4, 70);
    lv_obj_set_y(ui_lbMainSlotCell4, -130);
    lv_obj_set_align(ui_lbMainSlotCell4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell4, "Cell 4:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell4, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell4Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell4Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell4Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell4Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell4Value, -130);
    lv_obj_set_align(ui_lbMainSlotCell4Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell4Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell4Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell5 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell5, 70);
    lv_obj_set_y(ui_lbMainSlotCell5, -110);
    lv_obj_set_align(ui_lbMainSlotCell5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell5, "Cell 5:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell5Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell5Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell5Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell5Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell5Value, -110);
    lv_obj_set_align(ui_lbMainSlotCell5Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell5Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell5Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell6 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell6, 70);
    lv_obj_set_y(ui_lbMainSlotCell6, -90);
    lv_obj_set_align(ui_lbMainSlotCell6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell6, "Cell 6:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell6Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell6Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell6Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell6Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell6Value, -90);
    lv_obj_set_align(ui_lbMainSlotCell6Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell6Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell6Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell7 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell7, 70);
    lv_obj_set_y(ui_lbMainSlotCell7, -70);
    lv_obj_set_align(ui_lbMainSlotCell7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell7, "Cell 7:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell7, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell7Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell7Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell7Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell7Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell7Value, -70);
    lv_obj_set_align(ui_lbMainSlotCell7Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell7Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell7Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell8 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell8, 70);
    lv_obj_set_y(ui_lbMainSlotCell8, -50);
    lv_obj_set_align(ui_lbMainSlotCell8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell8, "Cell 8:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell8Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell8Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell8Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell8Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell8Value, -50);
    lv_obj_set_align(ui_lbMainSlotCell8Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell8Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell8Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell9 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell9, 70);
    lv_obj_set_y(ui_lbMainSlotCell9, -30);
    lv_obj_set_align(ui_lbMainSlotCell9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell9, "Cell 9:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell9Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell9Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell9Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell9Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell9Value, -30);
    lv_obj_set_align(ui_lbMainSlotCell9Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell9Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell9Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell10 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell10, 67);
    lv_obj_set_y(ui_lbMainSlotCell10, -10);
    lv_obj_set_align(ui_lbMainSlotCell10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell10, "Cell 10:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell10, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell10Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell10Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell10Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell10Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell10Value, -10);
    lv_obj_set_align(ui_lbMainSlotCell10Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell10Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell10Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell11 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell11, 67);
    lv_obj_set_y(ui_lbMainSlotCell11, 10);
    lv_obj_set_align(ui_lbMainSlotCell11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell11, "Cell 11:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell11Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell11Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell11Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell11Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell11Value, 10);
    lv_obj_set_align(ui_lbMainSlotCell11Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell11Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell11Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell12 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell12, 67);
    lv_obj_set_y(ui_lbMainSlotCell12, 30);
    lv_obj_set_align(ui_lbMainSlotCell12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell12, "Cell 12:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell12Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell12Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell12Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell12Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell12Value, 30);
    lv_obj_set_align(ui_lbMainSlotCell12Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell12Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell12Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell13 = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell13, 67);
    lv_obj_set_y(ui_lbMainSlotCell13, 50);
    lv_obj_set_align(ui_lbMainSlotCell13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell13, "Cell 13:");
    lv_obj_set_style_text_font(ui_lbMainSlotCell13, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotCell13Value = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotCell13Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotCell13Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotCell13Value, 150);
    lv_obj_set_y(ui_lbMainSlotCell13Value, 50);
    lv_obj_set_align(ui_lbMainSlotCell13Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotCell13Value, "4.086V");
    lv_obj_set_style_text_font(ui_lbMainSlotCell13Value, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotACCUInt = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotACCUInt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotACCUInt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotACCUInt, 52);
    lv_obj_set_y(ui_lbMainSlotACCUInt, 70);
    lv_obj_set_align(ui_lbMainSlotACCUInt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotACCUInt, "ACCU Int:");
    lv_obj_set_style_text_font(ui_lbMainSlotACCUInt, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotACCUIntValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotACCUIntValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotACCUIntValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotACCUIntValue, 150);
    lv_obj_set_y(ui_lbMainSlotACCUIntValue, 70);
    lv_obj_set_align(ui_lbMainSlotACCUIntValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotACCUIntValue, "0");
    lv_obj_set_style_text_font(ui_lbMainSlotACCUIntValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotACCUFrac = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotACCUFrac, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotACCUFrac, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotACCUFrac, 51);
    lv_obj_set_y(ui_lbMainSlotACCUFrac, 90);
    lv_obj_set_align(ui_lbMainSlotACCUFrac, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotACCUFrac, "ACCU Frc:");
    lv_obj_set_style_text_font(ui_lbMainSlotACCUFrac, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotACCUFracValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotACCUFracValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotACCUFracValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotACCUFracValue, 150);
    lv_obj_set_y(ui_lbMainSlotACCUFracValue, 90);
    lv_obj_set_align(ui_lbMainSlotACCUFracValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotACCUFracValue, "33355");
    lv_obj_set_style_text_font(ui_lbMainSlotACCUFracValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotACCUTime = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotACCUTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotACCUTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotACCUTime, 51);
    lv_obj_set_y(ui_lbMainSlotACCUTime, 110);
    lv_obj_set_align(ui_lbMainSlotACCUTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotACCUTime, "ACCU Tm:");
    lv_obj_set_style_text_font(ui_lbMainSlotACCUTime, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotACCUTimeValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotACCUTimeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotACCUTimeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotACCUTimeValue, 150);
    lv_obj_set_y(ui_lbMainSlotACCUTimeValue, 110);
    lv_obj_set_align(ui_lbMainSlotACCUTimeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotACCUTimeValue, "371");
    lv_obj_set_style_text_font(ui_lbMainSlotACCUTimeValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSafetyA = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSafetyA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSafetyA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSafetyA, 57);
    lv_obj_set_y(ui_lbMainSlotSafetyA, 130);
    lv_obj_set_align(ui_lbMainSlotSafetyA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSafetyA, "Safety A:");
    lv_obj_set_style_text_font(ui_lbMainSlotSafetyA, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSafetyAValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSafetyAValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSafetyAValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSafetyAValue, 150);
    lv_obj_set_y(ui_lbMainSlotSafetyAValue, 130);
    lv_obj_set_align(ui_lbMainSlotSafetyAValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSafetyAValue, "0");
    lv_obj_set_style_text_font(ui_lbMainSlotSafetyAValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSafetyB = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSafetyB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSafetyB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSafetyB, 57);
    lv_obj_set_y(ui_lbMainSlotSafetyB, 150);
    lv_obj_set_align(ui_lbMainSlotSafetyB, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSafetyB, "Safety B:");
    lv_obj_set_style_text_font(ui_lbMainSlotSafetyB, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSafetyBValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSafetyBValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSafetyBValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSafetyBValue, 150);
    lv_obj_set_y(ui_lbMainSlotSafetyBValue, 150);
    lv_obj_set_align(ui_lbMainSlotSafetyBValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSafetyBValue, "0");
    lv_obj_set_style_text_font(ui_lbMainSlotSafetyBValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSafetyC = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSafetyC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSafetyC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSafetyC, 57);
    lv_obj_set_y(ui_lbMainSlotSafetyC, 170);
    lv_obj_set_align(ui_lbMainSlotSafetyC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSafetyC, "Safety C:");
    lv_obj_set_style_text_font(ui_lbMainSlotSafetyC, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbMainSlotSafetyCValue = lv_label_create(ui_imgMainSlotDetalBg);
    lv_obj_set_width(ui_lbMainSlotSafetyCValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbMainSlotSafetyCValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbMainSlotSafetyCValue, 150);
    lv_obj_set_y(ui_lbMainSlotSafetyCValue, 170);
    lv_obj_set_align(ui_lbMainSlotSafetyCValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbMainSlotSafetyCValue, "0");
    lv_obj_set_style_text_font(ui_lbMainSlotSafetyCValue, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ibtMainManualSwap = lv_imgbtn_create(ui_imgMainSlotDetalBg);
    lv_imgbtn_set_src(ui_ibtMainManualSwap, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_imgmainmanualswapbat_png, NULL);
    lv_obj_set_width(ui_ibtMainManualSwap, 64);
    lv_obj_set_height(ui_ibtMainManualSwap, 64);
    lv_obj_set_x(ui_ibtMainManualSwap, 231);
    lv_obj_set_y(ui_ibtMainManualSwap, 177);
    lv_obj_set_align(ui_ibtMainManualSwap, LV_ALIGN_CENTER);

    ui_imgMainBotbotEmptyPin = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainBotbotEmptyPin, &ui_img_scrmain_robotlowbattery_png);
    lv_obj_set_width(ui_imgMainBotbotEmptyPin, LV_SIZE_CONTENT);   /// 162
    lv_obj_set_height(ui_imgMainBotbotEmptyPin, LV_SIZE_CONTENT);    /// 162
    lv_obj_set_x(ui_imgMainBotbotEmptyPin, 287);
    lv_obj_set_y(ui_imgMainBotbotEmptyPin, 154);
    lv_obj_set_align(ui_imgMainBotbotEmptyPin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainBotbotEmptyPin, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainBotbotEmptyPin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainRobotFullPin = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainRobotFullPin, &ui_img_scrmain_robotfullbattery_png);
    lv_obj_set_width(ui_imgMainRobotFullPin, LV_SIZE_CONTENT);   /// 163
    lv_obj_set_height(ui_imgMainRobotFullPin, LV_SIZE_CONTENT);    /// 163
    lv_obj_set_x(ui_imgMainRobotFullPin, 286);
    lv_obj_set_y(ui_imgMainRobotFullPin, 154);
    lv_obj_set_align(ui_imgMainRobotFullPin, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainRobotFullPin, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainRobotFullPin, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainRobotCharging = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainRobotCharging, &ui_img_scrmain_robotcharging_png);
    lv_obj_set_width(ui_imgMainRobotCharging, LV_SIZE_CONTENT);   /// 190
    lv_obj_set_height(ui_imgMainRobotCharging, LV_SIZE_CONTENT);    /// 190
    lv_obj_set_x(ui_imgMainRobotCharging, 302);
    lv_obj_set_y(ui_imgMainRobotCharging, 142);
    lv_obj_set_align(ui_imgMainRobotCharging, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainRobotCharging, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainRobotCharging, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainRbToSlot1 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainRbToSlot1, &ui_img_imgmainrbtoslot1_png);
    lv_obj_set_width(ui_imgMainRbToSlot1, LV_SIZE_CONTENT);   /// 327
    lv_obj_set_height(ui_imgMainRbToSlot1, LV_SIZE_CONTENT);    /// 367
    lv_obj_set_x(ui_imgMainRbToSlot1, 32);
    lv_obj_set_y(ui_imgMainRbToSlot1, 25);
    lv_obj_set_align(ui_imgMainRbToSlot1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainRbToSlot1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainRbToSlot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainRbToSlot2 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainRbToSlot2, &ui_img_imgmainrbtoslot2_png);
    lv_obj_set_width(ui_imgMainRbToSlot2, LV_SIZE_CONTENT);   /// 327
    lv_obj_set_height(ui_imgMainRbToSlot2, LV_SIZE_CONTENT);    /// 282
    lv_obj_set_x(ui_imgMainRbToSlot2, 32);
    lv_obj_set_y(ui_imgMainRbToSlot2, 68);
    lv_obj_set_align(ui_imgMainRbToSlot2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainRbToSlot2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainRbToSlot2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainRbToSlot3 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainRbToSlot3, &ui_img_imgmainrbtoslot3_png);
    lv_obj_set_width(ui_imgMainRbToSlot3, LV_SIZE_CONTENT);   /// 327
    lv_obj_set_height(ui_imgMainRbToSlot3, LV_SIZE_CONTENT);    /// 197
    lv_obj_set_x(ui_imgMainRbToSlot3, 32);
    lv_obj_set_y(ui_imgMainRbToSlot3, 110);
    lv_obj_set_align(ui_imgMainRbToSlot3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainRbToSlot3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainRbToSlot3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainRbToSlot4 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainRbToSlot4, &ui_img_imgmainrbtoslot4_png);
    lv_obj_set_width(ui_imgMainRbToSlot4, LV_SIZE_CONTENT);   /// 327
    lv_obj_set_height(ui_imgMainRbToSlot4, LV_SIZE_CONTENT);    /// 112
    lv_obj_set_x(ui_imgMainRbToSlot4, 32);
    lv_obj_set_y(ui_imgMainRbToSlot4, 153);
    lv_obj_set_align(ui_imgMainRbToSlot4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainRbToSlot4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainRbToSlot4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainRbToSlot5 = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainRbToSlot5, &ui_img_imgmainrbtoslot5_png);
    lv_obj_set_width(ui_imgMainRbToSlot5, LV_SIZE_CONTENT);   /// 327
    lv_obj_set_height(ui_imgMainRbToSlot5, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_imgMainRbToSlot5, 32);
    lv_obj_set_y(ui_imgMainRbToSlot5, 195);
    lv_obj_set_align(ui_imgMainRbToSlot5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainRbToSlot5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainRbToSlot5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainBattery = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainBattery, &ui_img_scrmain_batteryicon_png);
    lv_obj_set_width(ui_imgMainBattery, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_height(ui_imgMainBattery, LV_SIZE_CONTENT);    /// 84
    lv_obj_set_x(ui_imgMainBattery, -65);
    lv_obj_set_y(ui_imgMainBattery, -139);
    lv_obj_set_align(ui_imgMainBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainBattery, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMainNotConnect = lv_img_create(ui_scrMain);
    lv_img_set_src(ui_imgMainNotConnect, &ui_img_scrnotconnecticon_png);
    lv_obj_set_width(ui_imgMainNotConnect, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_imgMainNotConnect, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_imgMainNotConnect, 312);
    lv_obj_set_y(ui_imgMainNotConnect, -213);
    lv_obj_set_align(ui_imgMainNotConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMainNotConnect, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgMainNotConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ibtMainToSetting, ui_event_ibtMainToSetting, LV_EVENT_ALL, NULL);

}

void ui_scrMain_screen_destroy(void)
{
    if(ui_scrMain) lv_obj_del(ui_scrMain);

    // NULL screen variables
    ui_scrMain = NULL;
    ui_imgMainBackground = NULL;
    ui_lbMainTitle = NULL;
    ui_ibtMainToSetting = NULL;
    ui_imgMainSlotSerialDetail1 = NULL;
    ui_imgMainSlotSerialDetail2 = NULL;
    ui_imgMainSlotSerialDetail3 = NULL;
    ui_imgMainSlotSerialDetail4 = NULL;
    ui_imgMainSlotSerialDetail5 = NULL;
    ui_btMainSlot1 = NULL;
    ui_btMainSlot2 = NULL;
    ui_btMainSlot3 = NULL;
    ui_btMainSlot4 = NULL;
    ui_btMainSlot5 = NULL;
    ui_imgMainEmptyBat1 = NULL;
    ui_imgMainEmptyBat2 = NULL;
    ui_imgMainEmptyBat3 = NULL;
    ui_imgMainEmptyBat4 = NULL;
    ui_imgMainEmptyBat5 = NULL;
    ui_barMainBatPercent1 = NULL;
    ui_barMainBatPercent2 = NULL;
    ui_barMainBatPercent3 = NULL;
    ui_barMainBatPercent4 = NULL;
    ui_barMainBatPercent5 = NULL;
    ui_imgMainBatWarn1 = NULL;
    ui_imgMainBatWarn2 = NULL;
    ui_imgMainBatWarn3 = NULL;
    ui_imgMainBatWarn4 = NULL;
    ui_imgMainBatWarn5 = NULL;
    ui_lbMainSlot1SOC = NULL;
    ui_lbMainSlot2SOC = NULL;
    ui_lbMainSlot3SOC = NULL;
    ui_lbMainSlot4SOC = NULL;
    ui_lbMainSlot5SOC = NULL;
    ui_lbMainVoltageSlot1 = NULL;
    ui_lbMainVoltageSlot2 = NULL;
    ui_lbMainVoltageSlot3 = NULL;
    ui_lbMainVoltageSlot4 = NULL;
    ui_lbMainVoltageSlot5 = NULL;
    ui_lbMainCapSlot1 = NULL;
    ui_lbMainCapSlot2 = NULL;
    ui_lbMainCapSlot3 = NULL;
    ui_lbMainCapSlot4 = NULL;
    ui_lbMainCapSlot5 = NULL;
    ui_imgMainSlotDetalBg = NULL;
    ui_lbMainSlotBMSState = NULL;
    ui_lbMainSlotBMSStateValue = NULL;
    ui_lbMainSlotCtrlRq = NULL;
    ui_lbMainSlotCtrlRqValue = NULL;
    ui_lbMainSlotCtrlRp = NULL;
    ui_lbMainSlotCtrlRpValue = NULL;
    ui_lbMainSlotFETCtrlP = NULL;
    ui_lbMainSlotFETCtrlPValue = NULL;
    ui_lbMainSlotFETStt = NULL;
    ui_lbMainSlotFETSttValue = NULL;
    ui_lbMainSlotAlarmBits = NULL;
    ui_lbMainSlotAlarmBitsValue = NULL;
    ui_lbMainSlotFault = NULL;
    ui_lbMainSlotFaultValue = NULL;
    ui_lbMainSlotPackVolt = NULL;
    ui_lbMainSlotPackVoltValue = NULL;
    ui_lbMainSlotStackVolt = NULL;
    ui_lbMainSlotStackVoltValue = NULL;
    ui_lbMainSlotPackCur = NULL;
    ui_lbMainSlotPackCurValue = NULL;
    ui_lbMainSlotIdVolt = NULL;
    ui_lbMainSlotIdVoltValue = NULL;
    ui_lbMainSlotPinPercent = NULL;
    ui_lbMainSlotPinPercentValue = NULL;
    ui_lbMainSlotTgPercent = NULL;
    ui_lbMainSlotTgPercentValue = NULL;
    ui_lbMainSlotCelRes = NULL;
    ui_lbMainSlotCelResValue = NULL;
    ui_lbMainSlotSocPer = NULL;
    ui_lbMainSlotSocPerValue = NULL;
    ui_lbMainSlotSOH = NULL;
    ui_lbMainSlotSOHValue = NULL;
    ui_lbMainSlotSinPar = NULL;
    ui_lbMainSlotSinParValue = NULL;
    ui_lbMainSlotTemp1 = NULL;
    ui_lbMainSlotTemp1Value = NULL;
    ui_lbMainSlotTemp2 = NULL;
    ui_lbMainSlotTemp2Value = NULL;
    ui_lbMainSlotTemp3 = NULL;
    ui_lbMainSlotTemp3Value = NULL;
    ui_lbMainSlotCell1 = NULL;
    ui_lbMainSlotCell1Value = NULL;
    ui_lbMainSlotCell2 = NULL;
    ui_lbMainSlotCell2Value = NULL;
    ui_lbMainSlotCell3 = NULL;
    ui_lbMainSlotCell3Value = NULL;
    ui_lbMainSlotCell4 = NULL;
    ui_lbMainSlotCell4Value = NULL;
    ui_lbMainSlotCell5 = NULL;
    ui_lbMainSlotCell5Value = NULL;
    ui_lbMainSlotCell6 = NULL;
    ui_lbMainSlotCell6Value = NULL;
    ui_lbMainSlotCell7 = NULL;
    ui_lbMainSlotCell7Value = NULL;
    ui_lbMainSlotCell8 = NULL;
    ui_lbMainSlotCell8Value = NULL;
    ui_lbMainSlotCell9 = NULL;
    ui_lbMainSlotCell9Value = NULL;
    ui_lbMainSlotCell10 = NULL;
    ui_lbMainSlotCell10Value = NULL;
    ui_lbMainSlotCell11 = NULL;
    ui_lbMainSlotCell11Value = NULL;
    ui_lbMainSlotCell12 = NULL;
    ui_lbMainSlotCell12Value = NULL;
    ui_lbMainSlotCell13 = NULL;
    ui_lbMainSlotCell13Value = NULL;
    ui_lbMainSlotACCUInt = NULL;
    ui_lbMainSlotACCUIntValue = NULL;
    ui_lbMainSlotACCUFrac = NULL;
    ui_lbMainSlotACCUFracValue = NULL;
    ui_lbMainSlotACCUTime = NULL;
    ui_lbMainSlotACCUTimeValue = NULL;
    ui_lbMainSlotSafetyA = NULL;
    ui_lbMainSlotSafetyAValue = NULL;
    ui_lbMainSlotSafetyB = NULL;
    ui_lbMainSlotSafetyBValue = NULL;
    ui_lbMainSlotSafetyC = NULL;
    ui_lbMainSlotSafetyCValue = NULL;
    ui_ibtMainManualSwap = NULL;
    ui_imgMainBotbotEmptyPin = NULL;
    ui_imgMainRobotFullPin = NULL;
    ui_imgMainRobotCharging = NULL;
    ui_imgMainRbToSlot1 = NULL;
    ui_imgMainRbToSlot2 = NULL;
    ui_imgMainRbToSlot3 = NULL;
    ui_imgMainRbToSlot4 = NULL;
    ui_imgMainRbToSlot5 = NULL;
    ui_imgMainBattery = NULL;
    ui_imgMainNotConnect = NULL;

}
