// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_scrManualControl12 = NULL;
lv_obj_t * ui_vmologo2 = NULL;
lv_obj_t * ui_manualstep12label = NULL;
lv_obj_t * ui_robotbackcontainer = NULL;
lv_obj_t * ui_robotback = NULL;
lv_obj_t * ui_backbat1 = NULL;
lv_obj_t * ui_backbat2 = NULL;
lv_obj_t * ui_btngrpcontainer1 = NULL;
lv_obj_t * ui_chooseb1container = NULL;
lv_obj_t * ui_chooseb2container = NULL;
lv_obj_t * ui_backtomainbtn = NULL;
// event funtions
void ui_event_chooseb1container_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrManualControl22, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrManualControl22_screen_init);
    }
}

void ui_event_chooseb2container_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrManualControl22, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrManualControl22_screen_init);
    }
}

void ui_event_backtomainbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrMain_screen_init);
    }
}

// build funtions

void ui_scrManualControl12_screen_init(void)
{
    ui_scrManualControl12 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrManualControl12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrManualControl12, &ui_img_143516147, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vmologo2 = lv_img_create(ui_scrManualControl12);
    lv_img_set_src(ui_vmologo2, &ui_img_vmo_logo2_png);
    lv_obj_set_width(ui_vmologo2, LV_SIZE_CONTENT);   /// 216
    lv_obj_set_height(ui_vmologo2, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_vmologo2, 289);
    lv_obj_set_y(ui_vmologo2, 218);
    lv_obj_set_align(ui_vmologo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vmologo2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_vmologo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_manualstep12label = lv_label_create(ui_scrManualControl12);
    lv_obj_set_width(ui_manualstep12label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_manualstep12label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_manualstep12label, 233);
    lv_obj_set_y(ui_manualstep12label, -188);
    lv_obj_set_align(ui_manualstep12label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_manualstep12label, "STEP 1/2: \nSELECT BATTERY \nON THE ROBOT");
    lv_obj_set_style_text_color(ui_manualstep12label, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_manualstep12label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_manualstep12label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_manualstep12label, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_robotbackcontainer = lv_obj_create(ui_scrManualControl12);
    lv_obj_remove_style_all(ui_robotbackcontainer);
    lv_obj_set_width(ui_robotbackcontainer, 457);
    lv_obj_set_height(ui_robotbackcontainer, 480);
    lv_obj_set_x(ui_robotbackcontainer, -116);
    lv_obj_set_y(ui_robotbackcontainer, 0);
    lv_obj_set_align(ui_robotbackcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_robotbackcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_robotback = lv_img_create(ui_robotbackcontainer);
    lv_img_set_src(ui_robotback, &ui_img_1_blue_3_5_png);
    lv_obj_set_width(ui_robotback, LV_SIZE_CONTENT);   /// 468
    lv_obj_set_height(ui_robotback, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_robotback, -1);
    lv_obj_set_y(ui_robotback, 0);
    lv_obj_set_align(ui_robotback, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_robotback, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_robotback, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_robotback, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbat1 = lv_img_create(ui_robotbackcontainer);
    lv_img_set_src(ui_backbat1, &ui_img_1_blue_3_8_png);
    lv_obj_set_width(ui_backbat1, LV_SIZE_CONTENT);   /// 117
    lv_obj_set_height(ui_backbat1, LV_SIZE_CONTENT);    /// 83
    lv_obj_set_x(ui_backbat1, 114);
    lv_obj_set_y(ui_backbat1, -40);
    lv_obj_set_align(ui_backbat1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbat1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbat1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_backbat2 = lv_img_create(ui_robotbackcontainer);
    lv_img_set_src(ui_backbat2, &ui_img_1_blue_3_8_png);
    lv_obj_set_width(ui_backbat2, LV_SIZE_CONTENT);   /// 117
    lv_obj_set_height(ui_backbat2, LV_SIZE_CONTENT);    /// 83
    lv_obj_set_x(ui_backbat2, 116);
    lv_obj_set_y(ui_backbat2, 46);
    lv_obj_set_align(ui_backbat2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbat2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_backbat2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_backbat2, -15);

    ui_btngrpcontainer1 = lv_obj_create(ui_scrManualControl12);
    lv_obj_remove_style_all(ui_btngrpcontainer1);
    lv_obj_set_width(ui_btngrpcontainer1, 182);
    lv_obj_set_height(ui_btngrpcontainer1, 157);
    lv_obj_set_x(ui_btngrpcontainer1, 237);
    lv_obj_set_y(ui_btngrpcontainer1, 1);
    lv_obj_set_align(ui_btngrpcontainer1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_btngrpcontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chooseb1container = ui_buttoncontainer_create(ui_btngrpcontainer1);
    lv_obj_set_x(ui_chooseb1container, 1);
    lv_obj_set_y(ui_chooseb1container, -36);

    ui_chooseb2container = ui_buttoncontainer_create(ui_btngrpcontainer1);
    lv_obj_set_x(ui_chooseb2container, 0);
    lv_obj_set_y(ui_chooseb2container, 41);

    lv_label_set_text(ui_comp_get_child(ui_chooseb2container, UI_COMP_BUTTONCONTAINER_BUTONLABEL), "Battery 2");

    ui_backtomainbtn = lv_btn_create(ui_scrManualControl12);
    lv_obj_set_width(ui_backtomainbtn, 230);
    lv_obj_set_height(ui_backtomainbtn, 50);
    lv_obj_set_x(ui_backtomainbtn, 282);
    lv_obj_set_y(ui_backtomainbtn, 212);
    lv_obj_set_align(ui_backtomainbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backtomainbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backtomainbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_backtomainbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_comp_get_child(ui_chooseb1container, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_chooseb1container_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_chooseb2container, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_chooseb2container_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backtomainbtn, ui_event_backtomainbtn, LV_EVENT_ALL, NULL);

}

void ui_scrManualControl12_screen_destroy(void)
{
    if(ui_scrManualControl12) lv_obj_del(ui_scrManualControl12);

    // NULL screen variables
    ui_scrManualControl12 = NULL;
    ui_vmologo2 = NULL;
    ui_manualstep12label = NULL;
    ui_robotbackcontainer = NULL;
    ui_robotback = NULL;
    ui_backbat1 = NULL;
    ui_backbat2 = NULL;
    ui_btngrpcontainer1 = NULL;
    ui_chooseb1container = NULL;
    ui_chooseb2container = NULL;
    ui_backtomainbtn = NULL;

}
