// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_scrManualControl12 = NULL;
lv_obj_t * ui_scrmanual1vmologo = NULL;
lv_obj_t * ui_scrmanual1guidelabel = NULL;
lv_obj_t * ui_scrmanual1robotbackcontainer = NULL;
lv_obj_t * ui_scrmanual1robotbackimg = NULL;
lv_obj_t * ui_scrmanual1robotbat1img = NULL;
lv_obj_t * ui_scrmanual1robotbat2img = NULL;
lv_obj_t * ui_scrmanual1btngrpcontainer = NULL;
lv_obj_t * ui_chooseb1container = NULL;
lv_obj_t * ui_chooseb2container = NULL;
lv_obj_t * ui_scrmanual1backtomainbutton = NULL;
// event funtions
void ui_event_scrManualControl12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        fadeout_Animation(ui_scrmanual1robotbackimg, 0);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        _ui_opacity_set(ui_scrmanual1robotbackimg, 255);
    }
}

void ui_event_chooseb1container_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrManualControl22, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_scrManualControl22_screen_init);
        fnscrmanual1selectbat1(e);
    }
}

void ui_event_chooseb2container_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrManualControl22, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_scrManualControl22_screen_init);
        fnscrmanual1selectbat2(e);
    }
}

void ui_event_scrmanual1backtomainbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_scrMain_screen_init);
    }
}

// build funtions

void ui_scrManualControl12_screen_init(void)
{
    ui_scrManualControl12 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrManualControl12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrManualControl12, &ui_img_143516147, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrmanual1vmologo = lv_img_create(ui_scrManualControl12);
    lv_img_set_src(ui_scrmanual1vmologo, &ui_img_vmo_logo2_png);
    lv_obj_set_width(ui_scrmanual1vmologo, LV_SIZE_CONTENT);   /// 216
    lv_obj_set_height(ui_scrmanual1vmologo, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_scrmanual1vmologo, 289);
    lv_obj_set_y(ui_scrmanual1vmologo, 218);
    lv_obj_set_align(ui_scrmanual1vmologo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrmanual1vmologo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrmanual1vmologo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrmanual1guidelabel = lv_label_create(ui_scrManualControl12);
    lv_obj_set_width(ui_scrmanual1guidelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrmanual1guidelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrmanual1guidelabel, 233);
    lv_obj_set_y(ui_scrmanual1guidelabel, -188);
    lv_obj_set_align(ui_scrmanual1guidelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrmanual1guidelabel, "STEP 1/2: \nSELECT BATTERY \nON THE ROBOT");
    lv_obj_set_style_text_color(ui_scrmanual1guidelabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrmanual1guidelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_scrmanual1guidelabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrmanual1guidelabel, &ui_font_Bold, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrmanual1robotbackcontainer = lv_obj_create(ui_scrManualControl12);
    lv_obj_remove_style_all(ui_scrmanual1robotbackcontainer);
    lv_obj_set_width(ui_scrmanual1robotbackcontainer, 457);
    lv_obj_set_height(ui_scrmanual1robotbackcontainer, 480);
    lv_obj_set_x(ui_scrmanual1robotbackcontainer, -116);
    lv_obj_set_y(ui_scrmanual1robotbackcontainer, 0);
    lv_obj_set_align(ui_scrmanual1robotbackcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrmanual1robotbackcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrmanual1robotbackimg = lv_img_create(ui_scrmanual1robotbackcontainer);
    lv_img_set_src(ui_scrmanual1robotbackimg, &ui_img_1_blue_3_5_png);
    lv_obj_set_width(ui_scrmanual1robotbackimg, LV_SIZE_CONTENT);   /// 468
    lv_obj_set_height(ui_scrmanual1robotbackimg, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_scrmanual1robotbackimg, -1);
    lv_obj_set_y(ui_scrmanual1robotbackimg, 0);
    lv_obj_set_align(ui_scrmanual1robotbackimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrmanual1robotbackimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrmanual1robotbackimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_scrmanual1robotbackimg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrmanual1robotbat1img = lv_img_create(ui_scrmanual1robotbackcontainer);
    lv_img_set_src(ui_scrmanual1robotbat1img, &ui_img_1_blue_3_8_png);
    lv_obj_set_width(ui_scrmanual1robotbat1img, LV_SIZE_CONTENT);   /// 117
    lv_obj_set_height(ui_scrmanual1robotbat1img, LV_SIZE_CONTENT);    /// 83
    lv_obj_set_x(ui_scrmanual1robotbat1img, 114);
    lv_obj_set_y(ui_scrmanual1robotbat1img, -40);
    lv_obj_set_align(ui_scrmanual1robotbat1img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrmanual1robotbat1img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrmanual1robotbat1img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrmanual1robotbat2img = lv_img_create(ui_scrmanual1robotbackcontainer);
    lv_img_set_src(ui_scrmanual1robotbat2img, &ui_img_1_blue_3_8_png);
    lv_obj_set_width(ui_scrmanual1robotbat2img, LV_SIZE_CONTENT);   /// 117
    lv_obj_set_height(ui_scrmanual1robotbat2img, LV_SIZE_CONTENT);    /// 83
    lv_obj_set_x(ui_scrmanual1robotbat2img, 116);
    lv_obj_set_y(ui_scrmanual1robotbat2img, 46);
    lv_obj_set_align(ui_scrmanual1robotbat2img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrmanual1robotbat2img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrmanual1robotbat2img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_scrmanual1robotbat2img, -15);

    ui_scrmanual1btngrpcontainer = lv_obj_create(ui_scrManualControl12);
    lv_obj_remove_style_all(ui_scrmanual1btngrpcontainer);
    lv_obj_set_width(ui_scrmanual1btngrpcontainer, 182);
    lv_obj_set_height(ui_scrmanual1btngrpcontainer, 157);
    lv_obj_set_x(ui_scrmanual1btngrpcontainer, 237);
    lv_obj_set_y(ui_scrmanual1btngrpcontainer, 1);
    lv_obj_set_align(ui_scrmanual1btngrpcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrmanual1btngrpcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_chooseb1container = ui_buttoncontainer_create(ui_scrmanual1btngrpcontainer);
    lv_obj_set_x(ui_chooseb1container, 1);
    lv_obj_set_y(ui_chooseb1container, -36);

    ui_chooseb2container = ui_buttoncontainer_create(ui_scrmanual1btngrpcontainer);
    lv_obj_set_x(ui_chooseb2container, 0);
    lv_obj_set_y(ui_chooseb2container, 41);

    lv_label_set_text(ui_comp_get_child(ui_chooseb2container, UI_COMP_BUTTONCONTAINER_BUTONLABEL), "Battery 2");

    ui_scrmanual1backtomainbutton = lv_btn_create(ui_scrManualControl12);
    lv_obj_set_width(ui_scrmanual1backtomainbutton, 230);
    lv_obj_set_height(ui_scrmanual1backtomainbutton, 50);
    lv_obj_set_x(ui_scrmanual1backtomainbutton, 282);
    lv_obj_set_y(ui_scrmanual1backtomainbutton, 212);
    lv_obj_set_align(ui_scrmanual1backtomainbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrmanual1backtomainbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_scrmanual1backtomainbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_scrmanual1backtomainbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_comp_get_child(ui_chooseb1container, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_chooseb1container_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_comp_get_child(ui_chooseb2container, UI_COMP_BUTTONCONTAINER_BUTTON),
                        ui_event_chooseb2container_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrmanual1backtomainbutton, ui_event_scrmanual1backtomainbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrManualControl12, ui_event_scrManualControl12, LV_EVENT_ALL, NULL);

}

void ui_scrManualControl12_screen_destroy(void)
{
    if(ui_scrManualControl12) lv_obj_del(ui_scrManualControl12);

    // NULL screen variables
    ui_scrManualControl12 = NULL;
    ui_scrmanual1vmologo = NULL;
    ui_scrmanual1guidelabel = NULL;
    ui_scrmanual1robotbackcontainer = NULL;
    ui_scrmanual1robotbackimg = NULL;
    ui_scrmanual1robotbat1img = NULL;
    ui_scrmanual1robotbat2img = NULL;
    ui_scrmanual1btngrpcontainer = NULL;
    ui_chooseb1container = NULL;
    ui_chooseb2container = NULL;
    ui_scrmanual1backtomainbutton = NULL;

}
