// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_scrMainSlot = NULL;
lv_obj_t * ui_menucontainer2 = NULL;
lv_obj_t * ui_leftsidebar2 = NULL;
lv_obj_t * ui_batterycontainer2 = NULL;
lv_obj_t * ui_batteryicon2 = NULL;
lv_obj_t * ui_batterylabel2 = NULL;
lv_obj_t * ui_batterybtn2 = NULL;
lv_obj_t * ui_settingcontainer2 = NULL;
lv_obj_t * ui_settingicon2 = NULL;
lv_obj_t * ui_settinglabel2 = NULL;
lv_obj_t * ui_infocontainer2 = NULL;
lv_obj_t * ui_infoicon2 = NULL;
lv_obj_t * ui_infolabel2 = NULL;
lv_obj_t * ui_manualcontainer2 = NULL;
lv_obj_t * ui_maunicon2 = NULL;
lv_obj_t * ui_manlabel2 = NULL;
lv_obj_t * ui_manualbtn = NULL;
lv_obj_t * ui_manualbtn1 = NULL;
lv_obj_t * ui_slotbatterysttcontainer2 = NULL;
lv_obj_t * ui_slotbatterystt11 = NULL;
lv_obj_t * ui_slotbatterystt12 = NULL;
lv_obj_t * ui_slotbatterystt13 = NULL;
lv_obj_t * ui_slotbatterystt14 = NULL;
lv_obj_t * ui_slotbatterystt15 = NULL;
lv_obj_t * ui_lasttimecontainer1 = NULL;
lv_obj_t * ui_slottitle = NULL;
lv_obj_t * ui_slotdetailvalue = NULL;
lv_obj_t * ui_vmochargeralone = NULL;
lv_obj_t * ui_vmologo5 = NULL;
// event funtions
void ui_event_batterybtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_manualbtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_manualbtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrManualControl12, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrManualControl12_screen_init);
    }
}

void ui_event_vmologo5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrMain_screen_init);
    }
}

// build funtions

void ui_scrMainSlot_screen_init(void)
{
    ui_scrMainSlot = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrMainSlot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrMainSlot, &ui_img_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menucontainer2 = lv_obj_create(ui_scrMainSlot);
    lv_obj_remove_style_all(ui_menucontainer2);
    lv_obj_set_width(ui_menucontainer2, 800);
    lv_obj_set_height(ui_menucontainer2, 480);
    lv_obj_set_align(ui_menucontainer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menucontainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_menucontainer2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menucontainer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_menucontainer2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_menucontainer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_menucontainer2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_menucontainer2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_leftsidebar2 = lv_img_create(ui_menucontainer2);
    lv_img_set_src(ui_leftsidebar2, &ui_img_left_side_2_png);
    lv_obj_set_width(ui_leftsidebar2, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_leftsidebar2, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_leftsidebar2, -361);
    lv_obj_set_y(ui_leftsidebar2, 0);
    lv_obj_set_align(ui_leftsidebar2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_leftsidebar2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_leftsidebar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batterycontainer2 = lv_obj_create(ui_menucontainer2);
    lv_obj_remove_style_all(ui_batterycontainer2);
    lv_obj_set_width(ui_batterycontainer2, 72);
    lv_obj_set_height(ui_batterycontainer2, 55);
    lv_obj_set_x(ui_batterycontainer2, -361);
    lv_obj_set_y(ui_batterycontainer2, -181);
    lv_obj_set_align(ui_batterycontainer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_batterycontainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryicon2 = lv_img_create(ui_batterycontainer2);
    lv_img_set_src(ui_batteryicon2, &ui_img_battery_png);
    lv_obj_set_width(ui_batteryicon2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_batteryicon2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_batteryicon2, 2);
    lv_obj_set_y(ui_batteryicon2, -14);
    lv_obj_set_align(ui_batteryicon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batteryicon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_batteryicon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_batteryicon2, 350);

    ui_batterylabel2 = lv_label_create(ui_batterycontainer2);
    lv_obj_set_width(ui_batterylabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batterylabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batterylabel2, 0);
    lv_obj_set_y(ui_batterylabel2, 13);
    lv_obj_set_align(ui_batterylabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batterylabel2, "battery");
    lv_obj_set_style_text_color(ui_batterylabel2, lv_color_hex(0xDBE6FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batterylabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_batterylabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batterybtn2 = lv_btn_create(ui_batterycontainer2);
    lv_obj_set_width(ui_batterybtn2, 72);
    lv_obj_set_height(ui_batterybtn2, 55);
    lv_obj_set_align(ui_batterybtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batterybtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_batterybtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_batterybtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingcontainer2 = lv_obj_create(ui_menucontainer2);
    lv_obj_remove_style_all(ui_settingcontainer2);
    lv_obj_set_width(ui_settingcontainer2, 72);
    lv_obj_set_height(ui_settingcontainer2, 59);
    lv_obj_set_x(ui_settingcontainer2, -361);
    lv_obj_set_y(ui_settingcontainer2, 129);
    lv_obj_set_align(ui_settingcontainer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_settingcontainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingicon2 = lv_img_create(ui_settingcontainer2);
    lv_img_set_src(ui_settingicon2, &ui_img_setting_1_png);
    lv_obj_set_width(ui_settingicon2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_settingicon2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_settingicon2, 0);
    lv_obj_set_y(ui_settingicon2, -9);
    lv_obj_set_align(ui_settingicon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingicon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_settingicon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settinglabel2 = lv_label_create(ui_settingcontainer2);
    lv_obj_set_width(ui_settinglabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settinglabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settinglabel2, 0);
    lv_obj_set_y(ui_settinglabel2, 19);
    lv_obj_set_align(ui_settinglabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settinglabel2, "setting");
    lv_obj_set_style_text_color(ui_settinglabel2, lv_color_hex(0xDBE6FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settinglabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settinglabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_infocontainer2 = lv_obj_create(ui_menucontainer2);
    lv_obj_remove_style_all(ui_infocontainer2);
    lv_obj_set_width(ui_infocontainer2, 72);
    lv_obj_set_height(ui_infocontainer2, 59);
    lv_obj_set_x(ui_infocontainer2, -360);
    lv_obj_set_y(ui_infocontainer2, 206);
    lv_obj_set_align(ui_infocontainer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_infocontainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infoicon2 = lv_img_create(ui_infocontainer2);
    lv_img_set_src(ui_infoicon2, &ui_img_help_1_png);
    lv_obj_set_width(ui_infoicon2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_infoicon2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_infoicon2, 0);
    lv_obj_set_y(ui_infoicon2, -9);
    lv_obj_set_align(ui_infoicon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_infoicon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_infoicon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_infolabel2 = lv_label_create(ui_infocontainer2);
    lv_obj_set_width(ui_infolabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_infolabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_infolabel2, 0);
    lv_obj_set_y(ui_infolabel2, 19);
    lv_obj_set_align(ui_infolabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_infolabel2, "info");
    lv_obj_set_style_text_color(ui_infolabel2, lv_color_hex(0xDBE6FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_infolabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_infolabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_manualcontainer2 = lv_obj_create(ui_menucontainer2);
    lv_obj_remove_style_all(ui_manualcontainer2);
    lv_obj_set_width(ui_manualcontainer2, 72);
    lv_obj_set_height(ui_manualcontainer2, 59);
    lv_obj_set_x(ui_manualcontainer2, -361);
    lv_obj_set_y(ui_manualcontainer2, -110);
    lv_obj_set_align(ui_manualcontainer2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_manualcontainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_maunicon2 = lv_img_create(ui_manualcontainer2);
    lv_img_set_src(ui_maunicon2, &ui_img_manual_png);
    lv_obj_set_width(ui_maunicon2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_maunicon2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_maunicon2, 0);
    lv_obj_set_y(ui_maunicon2, -9);
    lv_obj_set_align(ui_maunicon2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_maunicon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_maunicon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_manlabel2 = lv_label_create(ui_manualcontainer2);
    lv_obj_set_width(ui_manlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_manlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_manlabel2, 1);
    lv_obj_set_y(ui_manlabel2, 19);
    lv_obj_set_align(ui_manlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_manlabel2, "manual");
    lv_obj_set_style_text_color(ui_manlabel2, lv_color_hex(0xDBE6FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_manlabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_manlabel2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_manualbtn = lv_btn_create(ui_manualcontainer2);
    lv_obj_set_width(ui_manualbtn, 72);
    lv_obj_set_height(ui_manualbtn, 55);
    lv_obj_set_align(ui_manualbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_manualbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_manualbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_manualbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_manualbtn1 = lv_btn_create(ui_manualcontainer2);
    lv_obj_set_width(ui_manualbtn1, 72);
    lv_obj_set_height(ui_manualbtn1, 55);
    lv_obj_set_align(ui_manualbtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_manualbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_manualbtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_manualbtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slotbatterysttcontainer2 = lv_obj_create(ui_scrMainSlot);
    lv_obj_remove_style_all(ui_slotbatterysttcontainer2);
    lv_obj_set_width(ui_slotbatterysttcontainer2, 443);
    lv_obj_set_height(ui_slotbatterysttcontainer2, 38);
    lv_obj_set_x(ui_slotbatterysttcontainer2, -97);
    lv_obj_set_y(ui_slotbatterysttcontainer2, 438);
    lv_obj_set_align(ui_slotbatterysttcontainer2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_slotbatterysttcontainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slotbatterystt11 = lv_obj_create(ui_slotbatterysttcontainer2);
    lv_obj_set_width(ui_slotbatterystt11, 25);
    lv_obj_set_height(ui_slotbatterystt11, 25);
    lv_obj_set_x(ui_slotbatterystt11, -196);
    lv_obj_set_y(ui_slotbatterystt11, -9);
    lv_obj_set_align(ui_slotbatterystt11, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slotbatterystt11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slotbatterystt11, lv_color_hex(0x46A279), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slotbatterystt11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_slotbatterystt11, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_slotbatterystt11, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_slotbatterystt12 = lv_obj_create(ui_slotbatterysttcontainer2);
    lv_obj_set_width(ui_slotbatterystt12, 20);
    lv_obj_set_height(ui_slotbatterystt12, 20);
    lv_obj_set_x(ui_slotbatterystt12, -166);
    lv_obj_set_y(ui_slotbatterystt12, -9);
    lv_obj_set_align(ui_slotbatterystt12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slotbatterystt12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slotbatterystt12, lv_color_hex(0x46A279), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slotbatterystt12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slotbatterystt13 = lv_obj_create(ui_slotbatterysttcontainer2);
    lv_obj_set_width(ui_slotbatterystt13, 20);
    lv_obj_set_height(ui_slotbatterystt13, 20);
    lv_obj_set_x(ui_slotbatterystt13, -136);
    lv_obj_set_y(ui_slotbatterystt13, -9);
    lv_obj_set_align(ui_slotbatterystt13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slotbatterystt13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slotbatterystt13, lv_color_hex(0x46A279), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slotbatterystt13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slotbatterystt14 = lv_obj_create(ui_slotbatterysttcontainer2);
    lv_obj_set_width(ui_slotbatterystt14, 20);
    lv_obj_set_height(ui_slotbatterystt14, 20);
    lv_obj_set_x(ui_slotbatterystt14, -106);
    lv_obj_set_y(ui_slotbatterystt14, -9);
    lv_obj_set_align(ui_slotbatterystt14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slotbatterystt14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slotbatterystt14, lv_color_hex(0xEE3A29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slotbatterystt14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slotbatterystt15 = lv_obj_create(ui_slotbatterysttcontainer2);
    lv_obj_set_width(ui_slotbatterystt15, 20);
    lv_obj_set_height(ui_slotbatterystt15, 20);
    lv_obj_set_x(ui_slotbatterystt15, -76);
    lv_obj_set_y(ui_slotbatterystt15, -9);
    lv_obj_set_align(ui_slotbatterystt15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slotbatterystt15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lasttimecontainer1 = lv_obj_create(ui_scrMainSlot);
    lv_obj_remove_style_all(ui_lasttimecontainer1);
    lv_obj_set_width(ui_lasttimecontainer1, 695);
    lv_obj_set_height(ui_lasttimecontainer1, 423);
    lv_obj_set_x(ui_lasttimecontainer1, 39);
    lv_obj_set_y(ui_lasttimecontainer1, -19);
    lv_obj_set_align(ui_lasttimecontainer1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_lasttimecontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_lasttimecontainer1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lasttimecontainer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lasttimecontainer1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_lasttimecontainer1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slottitle = lv_label_create(ui_lasttimecontainer1);
    lv_obj_set_width(ui_slottitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slottitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slottitle, 0);
    lv_obj_set_y(ui_slottitle, -175);
    lv_obj_set_align(ui_slottitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_slottitle, "SLOT X");
    lv_obj_set_style_text_color(ui_slottitle, lv_color_hex(0x314C83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slottitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_slottitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slottitle, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slotdetailvalue = lv_label_create(ui_lasttimecontainer1);
    lv_obj_set_width(ui_slotdetailvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slotdetailvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_slotdetailvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_slotdetailvalue, "<blank>");
    lv_obj_set_style_text_color(ui_slotdetailvalue, lv_color_hex(0x314C83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_slotdetailvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_slotdetailvalue, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vmochargeralone = lv_img_create(ui_scrMainSlot);
    lv_img_set_src(ui_vmochargeralone, &ui_img_vmocharger_png);
    lv_obj_set_width(ui_vmochargeralone, LV_SIZE_CONTENT);   /// 282
    lv_obj_set_height(ui_vmochargeralone, LV_SIZE_CONTENT);    /// 365
    lv_obj_set_x(ui_vmochargeralone, 58);
    lv_obj_set_y(ui_vmochargeralone, 13);
    lv_obj_set_align(ui_vmochargeralone, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vmochargeralone, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_vmochargeralone, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_vmochargeralone, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vmologo5 = lv_img_create(ui_scrMainSlot);
    lv_img_set_src(ui_vmologo5, &ui_img_vmo_logo2_png);
    lv_obj_set_width(ui_vmologo5, LV_SIZE_CONTENT);   /// 216
    lv_obj_set_height(ui_vmologo5, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_vmologo5, 289);
    lv_obj_set_y(ui_vmologo5, 218);
    lv_obj_set_align(ui_vmologo5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vmologo5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_vmologo5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_batterybtn2, ui_event_batterybtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_manualbtn, ui_event_manualbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_manualbtn1, ui_event_manualbtn1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vmologo5, ui_event_vmologo5, LV_EVENT_ALL, NULL);

}

void ui_scrMainSlot_screen_destroy(void)
{
    if(ui_scrMainSlot) lv_obj_del(ui_scrMainSlot);

    // NULL screen variables
    ui_scrMainSlot = NULL;
    ui_menucontainer2 = NULL;
    ui_leftsidebar2 = NULL;
    ui_batterycontainer2 = NULL;
    ui_batteryicon2 = NULL;
    ui_batterylabel2 = NULL;
    ui_batterybtn2 = NULL;
    ui_settingcontainer2 = NULL;
    ui_settingicon2 = NULL;
    ui_settinglabel2 = NULL;
    ui_infocontainer2 = NULL;
    ui_infoicon2 = NULL;
    ui_infolabel2 = NULL;
    ui_manualcontainer2 = NULL;
    ui_maunicon2 = NULL;
    ui_manlabel2 = NULL;
    ui_manualbtn = NULL;
    ui_manualbtn1 = NULL;
    ui_slotbatterysttcontainer2 = NULL;
    ui_slotbatterystt11 = NULL;
    ui_slotbatterystt12 = NULL;
    ui_slotbatterystt13 = NULL;
    ui_slotbatterystt14 = NULL;
    ui_slotbatterystt15 = NULL;
    ui_lasttimecontainer1 = NULL;
    ui_slottitle = NULL;
    ui_slotdetailvalue = NULL;
    ui_vmochargeralone = NULL;
    ui_vmologo5 = NULL;

}
