// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRSPLASH_H
#define UI_SCRSPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrSplash
extern void ui_scrSplash_screen_init(void);
extern void ui_scrSplash_screen_destroy(void);
<<<<<<< HEAD
extern lv_obj_t * ui_scrSplash;
extern lv_obj_t * ui_barSplashLoading;
extern lv_obj_t * ui_lbSplashLoadProgress;
extern lv_obj_t * ui_Image1;
=======
extern lv_obj_t* ui_scrSplash;
extern lv_obj_t* ui_imgSplashBackground;
extern lv_obj_t* ui_imgSplashIconLoading;
extern lv_obj_t* ui_barSplashLoading;
extern lv_obj_t* ui_lbSplashLoadProgress;
>>>>>>> parent of 7c27c3f (Merge pull request #7 from phamnamhien/20251218_cleancode)
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
