// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

<<<<<<< HEAD
lv_obj_t * ui_scrSplash = NULL;
lv_obj_t * ui_barSplashLoading = NULL;
lv_obj_t * ui_lbSplashLoadProgress = NULL;
lv_obj_t * ui_Image1 = NULL;
=======
lv_obj_t* ui_scrSplash = NULL;
lv_obj_t* ui_imgSplashBackground = NULL;
lv_obj_t* ui_imgSplashIconLoading = NULL;
lv_obj_t* ui_barSplashLoading = NULL;
lv_obj_t* ui_lbSplashLoadProgress = NULL;

>>>>>>> parent of 7c27c3f (Merge pull request #7 from phamnamhien/20251218_cleancode)
// event funtions

// build funtions

void
ui_scrSplash_screen_init(void) {
    ui_scrSplash = lv_obj_create(NULL);
<<<<<<< HEAD
    lv_obj_clear_flag(ui_scrSplash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrSplash, &ui_img_bg1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
=======
    lv_obj_clear_flag(ui_scrSplash, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_imgSplashBackground = lv_img_create(ui_scrSplash);
    lv_img_set_src(ui_imgSplashBackground, &ui_img_imgsplashbackground_png);
    lv_obj_set_width(ui_imgSplashBackground, LV_SIZE_CONTENT);  /// 800
    lv_obj_set_height(ui_imgSplashBackground, LV_SIZE_CONTENT); /// 480
    lv_obj_set_align(ui_imgSplashBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgSplashBackground, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_imgSplashBackground, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_imgSplashIconLoading = lv_img_create(ui_scrSplash);
    lv_img_set_src(ui_imgSplashIconLoading, &ui_img_robot_4_png);
    lv_obj_set_width(ui_imgSplashIconLoading, LV_SIZE_CONTENT);  /// 50
    lv_obj_set_height(ui_imgSplashIconLoading, LV_SIZE_CONTENT); /// 50
    lv_obj_set_x(ui_imgSplashIconLoading, -201);
    lv_obj_set_y(ui_imgSplashIconLoading, 201);
    lv_obj_set_align(ui_imgSplashIconLoading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgSplashIconLoading, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_imgSplashIconLoading, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags
>>>>>>> parent of 7c27c3f (Merge pull request #7 from phamnamhien/20251218_cleancode)

    ui_barSplashLoading = lv_bar_create(ui_scrSplash);
    lv_obj_set_width(ui_barSplashLoading, 800);
    lv_obj_set_height(ui_barSplashLoading, 10);
    lv_obj_set_x(ui_barSplashLoading, 0);
    lv_obj_set_y(ui_barSplashLoading, 235);
    lv_obj_set_align(ui_barSplashLoading, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barSplashLoading, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barSplashLoading, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barSplashLoading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_barSplashLoading, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barSplashLoading, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barSplashLoading, lv_color_hex(0x324A81), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barSplashLoading, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lbSplashLoadProgress = lv_label_create(ui_scrSplash);
    lv_obj_set_width(ui_lbSplashLoadProgress, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lbSplashLoadProgress, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_lbSplashLoadProgress, 0);
    lv_obj_set_y(ui_lbSplashLoadProgress, 200);
    lv_obj_set_align(ui_lbSplashLoadProgress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSplashLoadProgress, "system Initialization...");
<<<<<<< HEAD

    ui_Image1 = lv_img_create(ui_scrSplash);
    lv_img_set_src(ui_Image1, &ui_img_vmo_logo_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 525
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 89
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -50);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

=======
>>>>>>> parent of 7c27c3f (Merge pull request #7 from phamnamhien/20251218_cleancode)
}

void
ui_scrSplash_screen_destroy(void) {
    if (ui_scrSplash) {
        lv_obj_del(ui_scrSplash);
    }

    // NULL screen variables
    ui_scrSplash = NULL;
<<<<<<< HEAD
    ui_barSplashLoading = NULL;
    ui_lbSplashLoadProgress = NULL;
    ui_Image1 = NULL;

=======
    ui_imgSplashBackground = NULL;
    ui_imgSplashIconLoading = NULL;
    ui_barSplashLoading = NULL;
    ui_lbSplashLoadProgress = NULL;
>>>>>>> parent of 7c27c3f (Merge pull request #7 from phamnamhien/20251218_cleancode)
}
