// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern void ui_event_scrMain(lv_event_t * e);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_scrmainvmologo;
extern lv_obj_t * ui_scrmainmenucontainer;
extern lv_obj_t * ui_scrmainmenuleftsidebar;
extern lv_obj_t * ui_scrmainbatterycontainer;
extern lv_obj_t * ui_scrmainbatteryimg;
extern lv_obj_t * ui_scrmainbatterylabel;
extern void ui_event_scrmainbatterybutton(lv_event_t * e);
extern lv_obj_t * ui_scrmainbatterybutton;
extern lv_obj_t * ui_scrmainsettingcontainer;
extern lv_obj_t * ui_scrmainsettingimg;
extern lv_obj_t * ui_scrmainsettinglabel;
extern void ui_event_scrmainsettingbutton(lv_event_t * e);
extern lv_obj_t * ui_scrmainsettingbutton;
extern lv_obj_t * ui_scrmaininfocontainer;
extern lv_obj_t * ui_scrmaininfoimg;
extern lv_obj_t * ui_scrmaininfolabel;
extern lv_obj_t * ui_scrmainmanualcontainer;
extern lv_obj_t * ui_scrmainmanualimg;
extern lv_obj_t * ui_scrmainmanuallabel;
extern void ui_event_scrmainmanualbutton(lv_event_t * e);
extern lv_obj_t * ui_scrmainmanualbutton;
extern lv_obj_t * ui_scrmainstateofchargercontainer;
extern lv_obj_t * ui_scrmainstateofchargerpanel;
extern lv_obj_t * ui_scrmainstateofchargerlabel;
extern lv_obj_t * ui_scrmainstateofchargervalue;
extern void ui_event_scrmainbatslotscontainer(lv_event_t * e);
extern lv_obj_t * ui_scrmainbatslotscontainer;
extern lv_obj_t * ui_scrmainbatslotspanel;
extern lv_obj_t * ui_scrmainbatslotstitlelabel;
extern lv_obj_t * ui_scrmainbatslot1bar;
extern lv_obj_t * ui_scrmainbatslot2bar;
extern lv_obj_t * ui_scrmainbatslot3bar;
extern lv_obj_t * ui_scrmainbatslot4bar;
extern lv_obj_t * ui_scrmainbatslot5bar;
extern lv_obj_t * ui_scrmainbatslotslabel;
extern lv_obj_t * ui_scrmainchargerimg;
extern lv_obj_t * ui_scrmainlasttimecontainer;
extern lv_obj_t * ui_scrmainlasttimepanel;
extern lv_obj_t * ui_scrmainlasttimetitlelabel;
extern lv_obj_t * ui_scrmainlasttimelabel;
extern lv_obj_t * ui_scrmainnotconnectedimg;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

