// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRMANUALCONTROL12_H
#define UI_SCRMANUALCONTROL12_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrManualControl12
extern void ui_scrManualControl12_screen_init(void);
extern void ui_scrManualControl12_screen_destroy(void);
extern lv_obj_t * ui_scrManualControl12;
extern lv_obj_t * ui_vmologo2;
extern lv_obj_t * ui_manualstep12label;
extern lv_obj_t * ui_robotbackcontainer;
extern lv_obj_t * ui_robotback;
extern lv_obj_t * ui_backbat1;
extern lv_obj_t * ui_backbat2;
extern lv_obj_t * ui_btngrpcontainer1;
extern lv_obj_t * ui_chooseb1container;
extern void ui_event_chooseb1container_button(lv_event_t * e);
extern lv_obj_t * ui_chooseb2container;
extern void ui_event_chooseb2container_button(lv_event_t * e);
extern void ui_event_backtomainbtn(lv_event_t * e);
extern lv_obj_t * ui_backtomainbtn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

