// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_scrProcess = NULL;
lv_obj_t * ui_vmologo4 = NULL;
lv_obj_t * ui_runtimecontainer = NULL;
lv_obj_t * ui_runtimepanel = NULL;
lv_obj_t * ui_runtimetitle = NULL;
lv_obj_t * ui_runtimevalue = NULL;
lv_obj_t * ui_slotbatterysttcontainer1 = NULL;
lv_obj_t * ui_slotbatterystt6 = NULL;
lv_obj_t * ui_slotbatterystt7 = NULL;
lv_obj_t * ui_slotbatterystt8 = NULL;
lv_obj_t * ui_slotbatterystt9 = NULL;
lv_obj_t * ui_slotbatterystt10 = NULL;
lv_obj_t * ui_robotandcharge1 = NULL;
lv_obj_t * ui_Button1 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrMain_screen_init);
    }
}

// build funtions

void ui_scrProcess_screen_init(void)
{
    ui_scrProcess = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrProcess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrProcess, &ui_img_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vmologo4 = lv_img_create(ui_scrProcess);
    lv_img_set_src(ui_vmologo4, &ui_img_vmo_logo2_png);
    lv_obj_set_width(ui_vmologo4, LV_SIZE_CONTENT);   /// 216
    lv_obj_set_height(ui_vmologo4, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_vmologo4, 289);
    lv_obj_set_y(ui_vmologo4, 218);
    lv_obj_set_align(ui_vmologo4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_vmologo4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_vmologo4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_runtimecontainer = lv_obj_create(ui_scrProcess);
    lv_obj_remove_style_all(ui_runtimecontainer);
    lv_obj_set_width(ui_runtimecontainer, 270);
    lv_obj_set_height(ui_runtimecontainer, 117);
    lv_obj_set_x(ui_runtimecontainer, -238);
    lv_obj_set_y(ui_runtimecontainer, -166);
    lv_obj_set_align(ui_runtimecontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_runtimecontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_runtimepanel = lv_obj_create(ui_runtimecontainer);
    lv_obj_set_width(ui_runtimepanel, 261);
    lv_obj_set_height(ui_runtimepanel, 114);
    lv_obj_set_align(ui_runtimepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_runtimepanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_runtimepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_runtimepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_runtimepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_runtimepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_runtimepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_runtimepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_runtimepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_runtimepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_runtimetitle = lv_label_create(ui_runtimecontainer);
    lv_obj_set_width(ui_runtimetitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_runtimetitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_runtimetitle, 0);
    lv_obj_set_y(ui_runtimetitle, -39);
    lv_obj_set_align(ui_runtimetitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_runtimetitle, "Run times");
    lv_obj_set_style_text_color(ui_runtimetitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_runtimetitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_runtimetitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_runtimetitle, &ui_font_H11, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_runtimevalue = lv_label_create(ui_runtimecontainer);
    lv_obj_set_width(ui_runtimevalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_runtimevalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_runtimevalue, 0);
    lv_obj_set_y(ui_runtimevalue, 12);
    lv_obj_set_align(ui_runtimevalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_runtimevalue, "0s");
    lv_obj_set_style_text_color(ui_runtimevalue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_runtimevalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_runtimevalue, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slotbatterysttcontainer1 = lv_obj_create(ui_scrProcess);
    lv_obj_remove_style_all(ui_slotbatterysttcontainer1);
    lv_obj_set_width(ui_slotbatterysttcontainer1, 443);
    lv_obj_set_height(ui_slotbatterysttcontainer1, 50);
    lv_obj_set_x(ui_slotbatterysttcontainer1, -175);
    lv_obj_set_y(ui_slotbatterysttcontainer1, 429);
    lv_obj_set_align(ui_slotbatterysttcontainer1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_slotbatterysttcontainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slotbatterystt6 = lv_obj_create(ui_slotbatterysttcontainer1);
    lv_obj_set_width(ui_slotbatterystt6, 20);
    lv_obj_set_height(ui_slotbatterystt6, 20);
    lv_obj_set_x(ui_slotbatterystt6, -196);
    lv_obj_set_y(ui_slotbatterystt6, -14);
    lv_obj_set_align(ui_slotbatterystt6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slotbatterystt6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slotbatterystt6, lv_color_hex(0x46A279), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slotbatterystt6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_slotbatterystt6, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_slotbatterystt6, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_slotbatterystt7 = lv_obj_create(ui_slotbatterysttcontainer1);
    lv_obj_set_width(ui_slotbatterystt7, 20);
    lv_obj_set_height(ui_slotbatterystt7, 20);
    lv_obj_set_x(ui_slotbatterystt7, -166);
    lv_obj_set_y(ui_slotbatterystt7, -14);
    lv_obj_set_align(ui_slotbatterystt7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slotbatterystt7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slotbatterystt7, lv_color_hex(0x46A279), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slotbatterystt7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slotbatterystt8 = lv_obj_create(ui_slotbatterysttcontainer1);
    lv_obj_set_width(ui_slotbatterystt8, 20);
    lv_obj_set_height(ui_slotbatterystt8, 20);
    lv_obj_set_x(ui_slotbatterystt8, -136);
    lv_obj_set_y(ui_slotbatterystt8, -14);
    lv_obj_set_align(ui_slotbatterystt8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slotbatterystt8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slotbatterystt8, lv_color_hex(0x46A279), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slotbatterystt8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slotbatterystt9 = lv_obj_create(ui_slotbatterysttcontainer1);
    lv_obj_set_width(ui_slotbatterystt9, 20);
    lv_obj_set_height(ui_slotbatterystt9, 20);
    lv_obj_set_x(ui_slotbatterystt9, -106);
    lv_obj_set_y(ui_slotbatterystt9, -14);
    lv_obj_set_align(ui_slotbatterystt9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slotbatterystt9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_slotbatterystt9, lv_color_hex(0xEE3A29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slotbatterystt9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slotbatterystt10 = lv_obj_create(ui_slotbatterysttcontainer1);
    lv_obj_set_width(ui_slotbatterystt10, 20);
    lv_obj_set_height(ui_slotbatterystt10, 20);
    lv_obj_set_x(ui_slotbatterystt10, -76);
    lv_obj_set_y(ui_slotbatterystt10, -14);
    lv_obj_set_align(ui_slotbatterystt10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_slotbatterystt10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_robotandcharge1 = lv_img_create(ui_scrProcess);
    lv_img_set_src(ui_robotandcharge1, &ui_img_group_9_png);
    lv_obj_set_width(ui_robotandcharge1, LV_SIZE_CONTENT);   /// 282
    lv_obj_set_height(ui_robotandcharge1, LV_SIZE_CONTENT);    /// 374
    lv_obj_set_x(ui_robotandcharge1, 74);
    lv_obj_set_y(ui_robotandcharge1, 7);
    lv_obj_set_align(ui_robotandcharge1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_robotandcharge1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_robotandcharge1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_scrProcess);
    lv_obj_set_width(ui_Button1, 231);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 280);
    lv_obj_set_y(ui_Button1, 214);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_scrProcess_screen_destroy(void)
{
    if(ui_scrProcess) lv_obj_del(ui_scrProcess);

    // NULL screen variables
    ui_scrProcess = NULL;
    ui_vmologo4 = NULL;
    ui_runtimecontainer = NULL;
    ui_runtimepanel = NULL;
    ui_runtimetitle = NULL;
    ui_runtimevalue = NULL;
    ui_slotbatterysttcontainer1 = NULL;
    ui_slotbatterystt6 = NULL;
    ui_slotbatterystt7 = NULL;
    ui_slotbatterystt8 = NULL;
    ui_slotbatterystt9 = NULL;
    ui_slotbatterystt10 = NULL;
    ui_robotandcharge1 = NULL;
    ui_Button1 = NULL;

}
