// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRMAIN_H
#define UI_SCRMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMain
extern void ui_scrMain_screen_init(void);
extern void ui_scrMain_screen_destroy(void);
extern lv_obj_t * ui_scrMain;
extern lv_obj_t * ui_vmologo1;
extern lv_obj_t * ui_slotbatterysttcontainer;
extern lv_obj_t * ui_slotbatterystt1;
extern lv_obj_t * ui_slotbatterystt2;
extern lv_obj_t * ui_slotbatterystt3;
extern lv_obj_t * ui_slotbatterystt4;
extern lv_obj_t * ui_slotbatterystt5;
extern lv_obj_t * ui_stateofchargecontainer;
extern lv_obj_t * ui_stateofchargepanel;
extern lv_obj_t * ui_stateofchargelabel;
extern lv_obj_t * ui_statevalue;
extern lv_obj_t * ui_stateofchargecontainer1;
extern lv_obj_t * ui_stateofchargepanel1;
extern lv_obj_t * ui_stateofchargelabel1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_Bar5;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_chargeralone;
extern lv_obj_t * ui_lasttimecontainer;
extern lv_obj_t * ui_lastimepanel;
extern lv_obj_t * ui_lasttime;
extern lv_obj_t * ui_statevalue1;
extern lv_obj_t * ui_notconnectedicon;
extern lv_obj_t * ui_menucontainer;
extern lv_obj_t * ui_leftsidebar;
extern lv_obj_t * ui_batterycontainer;
extern lv_obj_t * ui_batteryicon;
extern lv_obj_t * ui_batterylabel;
extern void ui_event_batslotbutton(lv_event_t * e);
extern lv_obj_t * ui_batslotbutton;
extern lv_obj_t * ui_settingcontainer;
extern lv_obj_t * ui_settingicon;
extern lv_obj_t * ui_settinglabel;
extern lv_obj_t * ui_infocontainer;
extern lv_obj_t * ui_infoicon;
extern lv_obj_t * ui_infolabel;
extern lv_obj_t * ui_manualcontainer;
extern lv_obj_t * ui_maunicon;
extern lv_obj_t * ui_manlabel;
extern void ui_event_manualbutton(lv_event_t * e);
extern lv_obj_t * ui_manualbutton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

