// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_scrDetail = NULL;
lv_obj_t * ui_scrdetailmenucontainer = NULL;
lv_obj_t * ui_scrdetailmenuleftsidebar = NULL;
lv_obj_t * ui_scrdetailbatterycontainer = NULL;
lv_obj_t * ui_scrdetailbatteryimg = NULL;
lv_obj_t * ui_scrdetailbatterylabel = NULL;
lv_obj_t * ui_scrdetailbatterybutton = NULL;
lv_obj_t * ui_scrdetailsettingcontainer = NULL;
lv_obj_t * ui_scrdetailsettingimg = NULL;
lv_obj_t * ui_scrdetailsettinglabel = NULL;
lv_obj_t * ui_scrdetailinfocontainer = NULL;
lv_obj_t * ui_scrdetailinfoimg = NULL;
lv_obj_t * ui_scrdetailinfolabel = NULL;
lv_obj_t * ui_scrdetailmanualcontainer = NULL;
lv_obj_t * ui_scrdetailmanualimg = NULL;
lv_obj_t * ui_scrdetailmanuallabel = NULL;
lv_obj_t * ui_scrdetailmanualbutton = NULL;
lv_obj_t * ui_scrdetailslotssttcontainer = NULL;
lv_obj_t * ui_scrdetailslotssttpanel1 = NULL;
lv_obj_t * ui_scrdetailslotssttpanel2 = NULL;
lv_obj_t * ui_scrdetailslotssttpanel3 = NULL;
lv_obj_t * ui_scrdetailslotssttpanel4 = NULL;
lv_obj_t * ui_scrdetailslotssttpanel5 = NULL;
lv_obj_t * ui_scrdetaildatacontainer = NULL;
lv_obj_t * ui_scrdetaildataslottitlelabel = NULL;
lv_obj_t * ui_scrdetaildataslotvalue = NULL;
lv_obj_t * ui_scrdetaildataslotbackbutton = NULL;
lv_obj_t * ui_scrdetaildataslotnextbutton = NULL;
lv_obj_t * ui_scrdetailvmologo = NULL;
// event funtions
void ui_event_scrDetail(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_scrdetailbatterybutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_scrMain_screen_init);
        fnscrdetailbatterybuttonclicked(e);
    }
}

void ui_event_scrdetailmanualbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_scrMain_screen_init);
        fnscrdetailmanualbuttonclicked(e);
    }
}

void ui_event_scrdetaildataslotbackbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fnscrdetailbackslotbuttonclicked(e);
    }
}

void ui_event_scrdetaildataslotnextbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fnscrdetailnextslotbuttonclicked(e);
    }
}

void ui_event_scrdetailvmologo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_scrMain_screen_init);
        fnscrdetailbacktomainbuttonclicked(e);
    }
}

// build funtions

void ui_scrDetail_screen_init(void)
{
    ui_scrDetail = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrDetail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_scrDetail, &ui_img_bg2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailmenucontainer = lv_obj_create(ui_scrDetail);
    lv_obj_remove_style_all(ui_scrdetailmenucontainer);
    lv_obj_set_width(ui_scrdetailmenucontainer, 800);
    lv_obj_set_height(ui_scrdetailmenucontainer, 480);
    lv_obj_set_align(ui_scrdetailmenucontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetailmenucontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_scrdetailmenucontainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrdetailmenucontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_scrdetailmenucontainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_scrdetailmenucontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_scrdetailmenucontainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_scrdetailmenucontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailmenuleftsidebar = lv_img_create(ui_scrdetailmenucontainer);
    lv_img_set_src(ui_scrdetailmenuleftsidebar, &ui_img_left_side_2_png);
    lv_obj_set_width(ui_scrdetailmenuleftsidebar, LV_SIZE_CONTENT);   /// 79
    lv_obj_set_height(ui_scrdetailmenuleftsidebar, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_x(ui_scrdetailmenuleftsidebar, -361);
    lv_obj_set_y(ui_scrdetailmenuleftsidebar, 0);
    lv_obj_set_align(ui_scrdetailmenuleftsidebar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrdetailmenuleftsidebar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrdetailmenuleftsidebar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrdetailbatterycontainer = lv_obj_create(ui_scrdetailmenucontainer);
    lv_obj_remove_style_all(ui_scrdetailbatterycontainer);
    lv_obj_set_width(ui_scrdetailbatterycontainer, 72);
    lv_obj_set_height(ui_scrdetailbatterycontainer, 55);
    lv_obj_set_x(ui_scrdetailbatterycontainer, -361);
    lv_obj_set_y(ui_scrdetailbatterycontainer, -181);
    lv_obj_set_align(ui_scrdetailbatterycontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetailbatterycontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrdetailbatteryimg = lv_img_create(ui_scrdetailbatterycontainer);
    lv_img_set_src(ui_scrdetailbatteryimg, &ui_img_battery_png);
    lv_obj_set_width(ui_scrdetailbatteryimg, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_scrdetailbatteryimg, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_scrdetailbatteryimg, 2);
    lv_obj_set_y(ui_scrdetailbatteryimg, -14);
    lv_obj_set_align(ui_scrdetailbatteryimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrdetailbatteryimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrdetailbatteryimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_scrdetailbatteryimg, 350);

    ui_scrdetailbatterylabel = lv_label_create(ui_scrdetailbatterycontainer);
    lv_obj_set_width(ui_scrdetailbatterylabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrdetailbatterylabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrdetailbatterylabel, 0);
    lv_obj_set_y(ui_scrdetailbatterylabel, 13);
    lv_obj_set_align(ui_scrdetailbatterylabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrdetailbatterylabel, "battery");
    lv_obj_set_style_text_color(ui_scrdetailbatterylabel, lv_color_hex(0xDBE6FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrdetailbatterylabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrdetailbatterylabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailbatterybutton = lv_btn_create(ui_scrdetailbatterycontainer);
    lv_obj_set_width(ui_scrdetailbatterybutton, 72);
    lv_obj_set_height(ui_scrdetailbatterybutton, 55);
    lv_obj_set_align(ui_scrdetailbatterybutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrdetailbatterybutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_scrdetailbatterybutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_scrdetailbatterybutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailsettingcontainer = lv_obj_create(ui_scrdetailmenucontainer);
    lv_obj_remove_style_all(ui_scrdetailsettingcontainer);
    lv_obj_set_width(ui_scrdetailsettingcontainer, 72);
    lv_obj_set_height(ui_scrdetailsettingcontainer, 59);
    lv_obj_set_x(ui_scrdetailsettingcontainer, -361);
    lv_obj_set_y(ui_scrdetailsettingcontainer, 129);
    lv_obj_set_align(ui_scrdetailsettingcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetailsettingcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrdetailsettingimg = lv_img_create(ui_scrdetailsettingcontainer);
    lv_img_set_src(ui_scrdetailsettingimg, &ui_img_setting_1_png);
    lv_obj_set_width(ui_scrdetailsettingimg, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_scrdetailsettingimg, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_scrdetailsettingimg, 0);
    lv_obj_set_y(ui_scrdetailsettingimg, -9);
    lv_obj_set_align(ui_scrdetailsettingimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrdetailsettingimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrdetailsettingimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrdetailsettinglabel = lv_label_create(ui_scrdetailsettingcontainer);
    lv_obj_set_width(ui_scrdetailsettinglabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrdetailsettinglabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrdetailsettinglabel, 0);
    lv_obj_set_y(ui_scrdetailsettinglabel, 19);
    lv_obj_set_align(ui_scrdetailsettinglabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrdetailsettinglabel, "setting");
    lv_obj_set_style_text_color(ui_scrdetailsettinglabel, lv_color_hex(0xDBE6FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrdetailsettinglabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrdetailsettinglabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailinfocontainer = lv_obj_create(ui_scrdetailmenucontainer);
    lv_obj_remove_style_all(ui_scrdetailinfocontainer);
    lv_obj_set_width(ui_scrdetailinfocontainer, 72);
    lv_obj_set_height(ui_scrdetailinfocontainer, 59);
    lv_obj_set_x(ui_scrdetailinfocontainer, -360);
    lv_obj_set_y(ui_scrdetailinfocontainer, 206);
    lv_obj_set_align(ui_scrdetailinfocontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetailinfocontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrdetailinfoimg = lv_img_create(ui_scrdetailinfocontainer);
    lv_img_set_src(ui_scrdetailinfoimg, &ui_img_help_1_png);
    lv_obj_set_width(ui_scrdetailinfoimg, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_scrdetailinfoimg, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_scrdetailinfoimg, 0);
    lv_obj_set_y(ui_scrdetailinfoimg, -9);
    lv_obj_set_align(ui_scrdetailinfoimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrdetailinfoimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrdetailinfoimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrdetailinfolabel = lv_label_create(ui_scrdetailinfocontainer);
    lv_obj_set_width(ui_scrdetailinfolabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrdetailinfolabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrdetailinfolabel, 0);
    lv_obj_set_y(ui_scrdetailinfolabel, 19);
    lv_obj_set_align(ui_scrdetailinfolabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrdetailinfolabel, "info");
    lv_obj_set_style_text_color(ui_scrdetailinfolabel, lv_color_hex(0xDBE6FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrdetailinfolabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrdetailinfolabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailmanualcontainer = lv_obj_create(ui_scrdetailmenucontainer);
    lv_obj_remove_style_all(ui_scrdetailmanualcontainer);
    lv_obj_set_width(ui_scrdetailmanualcontainer, 72);
    lv_obj_set_height(ui_scrdetailmanualcontainer, 59);
    lv_obj_set_x(ui_scrdetailmanualcontainer, -361);
    lv_obj_set_y(ui_scrdetailmanualcontainer, -110);
    lv_obj_set_align(ui_scrdetailmanualcontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetailmanualcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrdetailmanualimg = lv_img_create(ui_scrdetailmanualcontainer);
    lv_img_set_src(ui_scrdetailmanualimg, &ui_img_manual_png);
    lv_obj_set_width(ui_scrdetailmanualimg, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_scrdetailmanualimg, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_scrdetailmanualimg, 0);
    lv_obj_set_y(ui_scrdetailmanualimg, -9);
    lv_obj_set_align(ui_scrdetailmanualimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrdetailmanualimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrdetailmanualimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrdetailmanuallabel = lv_label_create(ui_scrdetailmanualcontainer);
    lv_obj_set_width(ui_scrdetailmanuallabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrdetailmanuallabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrdetailmanuallabel, 1);
    lv_obj_set_y(ui_scrdetailmanuallabel, 19);
    lv_obj_set_align(ui_scrdetailmanuallabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrdetailmanuallabel, "manual");
    lv_obj_set_style_text_color(ui_scrdetailmanuallabel, lv_color_hex(0xDBE6FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrdetailmanuallabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrdetailmanuallabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailmanualbutton = lv_btn_create(ui_scrdetailmanualcontainer);
    lv_obj_set_width(ui_scrdetailmanualbutton, 72);
    lv_obj_set_height(ui_scrdetailmanualbutton, 55);
    lv_obj_set_align(ui_scrdetailmanualbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrdetailmanualbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_scrdetailmanualbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_scrdetailmanualbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailslotssttcontainer = lv_obj_create(ui_scrDetail);
    lv_obj_remove_style_all(ui_scrdetailslotssttcontainer);
    lv_obj_set_width(ui_scrdetailslotssttcontainer, 443);
    lv_obj_set_height(ui_scrdetailslotssttcontainer, 38);
    lv_obj_set_x(ui_scrdetailslotssttcontainer, -97);
    lv_obj_set_y(ui_scrdetailslotssttcontainer, 438);
    lv_obj_set_align(ui_scrdetailslotssttcontainer, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_scrdetailslotssttcontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrdetailslotssttpanel1 = lv_obj_create(ui_scrdetailslotssttcontainer);
    lv_obj_set_width(ui_scrdetailslotssttpanel1, 25);
    lv_obj_set_height(ui_scrdetailslotssttpanel1, 25);
    lv_obj_set_x(ui_scrdetailslotssttpanel1, -196);
    lv_obj_set_y(ui_scrdetailslotssttpanel1, -9);
    lv_obj_set_align(ui_scrdetailslotssttpanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetailslotssttpanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrdetailslotssttpanel1, lv_color_hex(0x46A279), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrdetailslotssttpanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_scrdetailslotssttpanel1, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_scrdetailslotssttpanel1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_scrdetailslotssttpanel2 = lv_obj_create(ui_scrdetailslotssttcontainer);
    lv_obj_set_width(ui_scrdetailslotssttpanel2, 20);
    lv_obj_set_height(ui_scrdetailslotssttpanel2, 20);
    lv_obj_set_x(ui_scrdetailslotssttpanel2, -166);
    lv_obj_set_y(ui_scrdetailslotssttpanel2, -9);
    lv_obj_set_align(ui_scrdetailslotssttpanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetailslotssttpanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrdetailslotssttpanel2, lv_color_hex(0x46A279), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrdetailslotssttpanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailslotssttpanel3 = lv_obj_create(ui_scrdetailslotssttcontainer);
    lv_obj_set_width(ui_scrdetailslotssttpanel3, 20);
    lv_obj_set_height(ui_scrdetailslotssttpanel3, 20);
    lv_obj_set_x(ui_scrdetailslotssttpanel3, -136);
    lv_obj_set_y(ui_scrdetailslotssttpanel3, -9);
    lv_obj_set_align(ui_scrdetailslotssttpanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetailslotssttpanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrdetailslotssttpanel3, lv_color_hex(0x46A279), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrdetailslotssttpanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailslotssttpanel4 = lv_obj_create(ui_scrdetailslotssttcontainer);
    lv_obj_set_width(ui_scrdetailslotssttpanel4, 20);
    lv_obj_set_height(ui_scrdetailslotssttpanel4, 20);
    lv_obj_set_x(ui_scrdetailslotssttpanel4, -106);
    lv_obj_set_y(ui_scrdetailslotssttpanel4, -9);
    lv_obj_set_align(ui_scrdetailslotssttpanel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetailslotssttpanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrdetailslotssttpanel4, lv_color_hex(0xEE3A29), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrdetailslotssttpanel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailslotssttpanel5 = lv_obj_create(ui_scrdetailslotssttcontainer);
    lv_obj_set_width(ui_scrdetailslotssttpanel5, 20);
    lv_obj_set_height(ui_scrdetailslotssttpanel5, 20);
    lv_obj_set_x(ui_scrdetailslotssttpanel5, -76);
    lv_obj_set_y(ui_scrdetailslotssttpanel5, -9);
    lv_obj_set_align(ui_scrdetailslotssttpanel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetailslotssttpanel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scrdetaildatacontainer = lv_obj_create(ui_scrDetail);
    lv_obj_remove_style_all(ui_scrdetaildatacontainer);
    lv_obj_set_width(ui_scrdetaildatacontainer, 695);
    lv_obj_set_height(ui_scrdetaildatacontainer, 423);
    lv_obj_set_x(ui_scrdetaildatacontainer, 39);
    lv_obj_set_y(ui_scrdetaildatacontainer, -19);
    lv_obj_set_align(ui_scrdetaildatacontainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_scrdetaildatacontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_scrdetaildatacontainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scrdetaildatacontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_scrdetaildatacontainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_scrdetaildatacontainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetaildataslottitlelabel = lv_label_create(ui_scrdetaildatacontainer);
    lv_obj_set_width(ui_scrdetaildataslottitlelabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrdetaildataslottitlelabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scrdetaildataslottitlelabel, 0);
    lv_obj_set_y(ui_scrdetaildataslottitlelabel, -175);
    lv_obj_set_align(ui_scrdetaildataslottitlelabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrdetaildataslottitlelabel, "SLOT X");
    lv_obj_set_style_text_color(ui_scrdetaildataslottitlelabel, lv_color_hex(0x314C83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrdetaildataslottitlelabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_scrdetaildataslottitlelabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrdetaildataslottitlelabel, &ui_font_H1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetaildataslotvalue = lv_label_create(ui_scrdetaildatacontainer);
    lv_obj_set_width(ui_scrdetaildataslotvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scrdetaildataslotvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_scrdetaildataslotvalue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scrdetaildataslotvalue, "<blank>");
    lv_obj_set_style_text_color(ui_scrdetaildataslotvalue, lv_color_hex(0x314C83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scrdetaildataslotvalue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scrdetaildataslotvalue, &ui_font_H2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetaildataslotbackbutton = lv_btn_create(ui_scrdetaildatacontainer);
    lv_obj_set_width(ui_scrdetaildataslotbackbutton, 150);
    lv_obj_set_height(ui_scrdetaildataslotbackbutton, 416);
    lv_obj_set_x(ui_scrdetaildataslotbackbutton, -269);
    lv_obj_set_y(ui_scrdetaildataslotbackbutton, 0);
    lv_obj_set_align(ui_scrdetaildataslotbackbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrdetaildataslotbackbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_scrdetaildataslotbackbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_scrdetaildataslotbackbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetaildataslotnextbutton = lv_btn_create(ui_scrdetaildatacontainer);
    lv_obj_set_width(ui_scrdetaildataslotnextbutton, 167);
    lv_obj_set_height(ui_scrdetaildataslotnextbutton, 416);
    lv_obj_set_x(ui_scrdetaildataslotnextbutton, 260);
    lv_obj_set_y(ui_scrdetaildataslotnextbutton, 2);
    lv_obj_set_align(ui_scrdetaildataslotnextbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrdetaildataslotnextbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_scrdetaildataslotnextbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_scrdetaildataslotnextbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scrdetailvmologo = lv_img_create(ui_scrDetail);
    lv_img_set_src(ui_scrdetailvmologo, &ui_img_vmo_logo2_png);
    lv_obj_set_width(ui_scrdetailvmologo, LV_SIZE_CONTENT);   /// 216
    lv_obj_set_height(ui_scrdetailvmologo, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_scrdetailvmologo, 289);
    lv_obj_set_y(ui_scrdetailvmologo, 218);
    lv_obj_set_align(ui_scrdetailvmologo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scrdetailvmologo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_scrdetailvmologo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_scrdetailbatterybutton, ui_event_scrdetailbatterybutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrdetailmanualbutton, ui_event_scrdetailmanualbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrdetaildataslotbackbutton, ui_event_scrdetaildataslotbackbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrdetaildataslotnextbutton, ui_event_scrdetaildataslotnextbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrdetailvmologo, ui_event_scrdetailvmologo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_scrDetail, ui_event_scrDetail, LV_EVENT_ALL, NULL);

}

void ui_scrDetail_screen_destroy(void)
{
    if(ui_scrDetail) lv_obj_del(ui_scrDetail);

    // NULL screen variables
    ui_scrDetail = NULL;
    ui_scrdetailmenucontainer = NULL;
    ui_scrdetailmenuleftsidebar = NULL;
    ui_scrdetailbatterycontainer = NULL;
    ui_scrdetailbatteryimg = NULL;
    ui_scrdetailbatterylabel = NULL;
    ui_scrdetailbatterybutton = NULL;
    ui_scrdetailsettingcontainer = NULL;
    ui_scrdetailsettingimg = NULL;
    ui_scrdetailsettinglabel = NULL;
    ui_scrdetailinfocontainer = NULL;
    ui_scrdetailinfoimg = NULL;
    ui_scrdetailinfolabel = NULL;
    ui_scrdetailmanualcontainer = NULL;
    ui_scrdetailmanualimg = NULL;
    ui_scrdetailmanuallabel = NULL;
    ui_scrdetailmanualbutton = NULL;
    ui_scrdetailslotssttcontainer = NULL;
    ui_scrdetailslotssttpanel1 = NULL;
    ui_scrdetailslotssttpanel2 = NULL;
    ui_scrdetailslotssttpanel3 = NULL;
    ui_scrdetailslotssttpanel4 = NULL;
    ui_scrdetailslotssttpanel5 = NULL;
    ui_scrdetaildatacontainer = NULL;
    ui_scrdetaildataslottitlelabel = NULL;
    ui_scrdetaildataslotvalue = NULL;
    ui_scrdetaildataslotbackbutton = NULL;
    ui_scrdetaildataslotnextbutton = NULL;
    ui_scrdetailvmologo = NULL;

}
