// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRMANUALCONTROL22_H
#define UI_SCRMANUALCONTROL22_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrManualControl22
extern void ui_scrManualControl22_screen_init(void);
extern void ui_scrManualControl22_screen_destroy(void);
extern lv_obj_t * ui_scrManualControl22;
extern lv_obj_t * ui_robotandcharge2;
extern lv_obj_t * ui_manualstep22label;
extern lv_obj_t * ui_vmologo3;
extern void ui_event_backtomainbtn2(lv_event_t * e);
extern lv_obj_t * ui_backtomainbtn2;
extern lv_obj_t * ui_btngrpcontainer2;
extern lv_obj_t * ui_chooses1container;
extern lv_obj_t * ui_chooses2container;
extern lv_obj_t * ui_chooses3container;
extern lv_obj_t * ui_chooses4container;
extern lv_obj_t * ui_chooses5container;
extern lv_obj_t * ui_slotvaluecontainner;
extern lv_obj_t * ui_slot1info;
extern lv_obj_t * ui_slot2info;
extern lv_obj_t * ui_slot3info;
extern lv_obj_t * ui_slot4info;
extern lv_obj_t * ui_slot5info;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

