// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRDETAIL_H
#define UI_SCRDETAIL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrDetail
extern void ui_scrDetail_screen_init(void);
extern void ui_scrDetail_screen_destroy(void);
extern void ui_event_scrDetail(lv_event_t * e);
extern lv_obj_t * ui_scrDetail;
extern lv_obj_t * ui_scrdetailmenucontainer;
extern lv_obj_t * ui_scrdetailmenuleftsidebar;
extern lv_obj_t * ui_scrdetailbatterycontainer;
extern lv_obj_t * ui_scrdetailbatteryimg;
extern lv_obj_t * ui_scrdetailbatterylabel;
extern void ui_event_scrdetailbatterybutton(lv_event_t * e);
extern lv_obj_t * ui_scrdetailbatterybutton;
extern lv_obj_t * ui_scrdetailsettingcontainer;
extern lv_obj_t * ui_scrdetailsettingimg;
extern lv_obj_t * ui_scrdetailsettinglabel;
extern lv_obj_t * ui_scrdetailinfocontainer;
extern lv_obj_t * ui_scrdetailinfoimg;
extern lv_obj_t * ui_scrdetailinfolabel;
extern lv_obj_t * ui_scrdetailmanualcontainer;
extern lv_obj_t * ui_scrdetailmanualimg;
extern lv_obj_t * ui_scrdetailmanuallabel;
extern void ui_event_scrdetailmanualbutton(lv_event_t * e);
extern lv_obj_t * ui_scrdetailmanualbutton;
extern lv_obj_t * ui_scrdetailslotssttcontainer;
extern lv_obj_t * ui_scrdetailslotssttpanel1;
extern lv_obj_t * ui_scrdetailslotssttpanel2;
extern lv_obj_t * ui_scrdetailslotssttpanel3;
extern lv_obj_t * ui_scrdetailslotssttpanel4;
extern lv_obj_t * ui_scrdetailslotssttpanel5;
extern lv_obj_t * ui_scrdetaildatacontainer;
extern lv_obj_t * ui_scrdetaildatapanel;
extern lv_obj_t * ui_scrdetaildataslottitlelabel;
extern lv_obj_t * ui_scrdetaildataslotvalue1;
extern lv_obj_t * ui_scrdetaildataslotvalue2;
extern lv_obj_t * ui_scrdetaildataslotvalue3;
extern lv_obj_t * ui_scrdetailvmologo;
extern void ui_event_scrdetailbacktomainbutton(lv_event_t * e);
extern lv_obj_t * ui_scrdetailbacktomainbutton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

