// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRPROCESS_H
#define UI_SCRPROCESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrProcess
extern void ui_scrProcess_screen_init(void);
extern void ui_scrProcess_screen_destroy(void);
extern void ui_event_scrProcess(lv_event_t * e);
extern lv_obj_t * ui_scrProcess;
extern lv_obj_t * ui_scrprocessstatecontainer;
extern lv_obj_t * ui_scrprocessstatepanel;
extern lv_obj_t * ui_scrprocessstatetitlelabel;
extern lv_obj_t * ui_scrprocessstatevalue;
extern lv_obj_t * ui_scrprocessvmologo;
extern lv_obj_t * ui_scrprocessruntimecontainer;
extern lv_obj_t * ui_scrprocessruntimepanel;
extern lv_obj_t * ui_scrprocessruntimetitle;
extern lv_obj_t * ui_scrprocessruntimevalue;
extern lv_obj_t * ui_scrprocessslotssttcontainer;
extern lv_obj_t * ui_scrprocessslotssttslot1panel;
extern lv_obj_t * ui_scrprocessslotssttslot2panel;
extern lv_obj_t * ui_scrprocessslotssttslot3panel;
extern lv_obj_t * ui_scrprocessslotssttslot4panel;
extern lv_obj_t * ui_scrprocessslotssttslot5panel;
extern lv_obj_t * ui_scrprocesschargerimg;
extern lv_obj_t * ui_scrprocessrobotimg;
extern void ui_event_scrprocessbacktomainbutton(lv_event_t * e);
extern lv_obj_t * ui_scrprocessbacktomainbutton;
extern lv_obj_t * ui_scrprocessprcontainer;
extern lv_obj_t * ui_scrprocessstopcontainer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

