// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#include "../ui.h"

lv_obj_t * ui_scrSetting = NULL;
lv_obj_t * ui_imgSettingBackground = NULL;
lv_obj_t * ui_lbSettingTitle = NULL;
lv_obj_t * ui_ibtSettingBackToMain = NULL;
// event funtions
void ui_event_ibtSettingBackToMain(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fnSettingBackToMainClicked(e);
    }
}

// build funtions

void ui_scrSetting_screen_init(void)
{
    ui_scrSetting = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgSettingBackground = lv_img_create(ui_scrSetting);
    lv_img_set_src(ui_imgSettingBackground, &ui_img_imgsettingbackground_png);
    lv_obj_set_width(ui_imgSettingBackground, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_imgSettingBackground, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_imgSettingBackground, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgSettingBackground, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgSettingBackground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lbSettingTitle = lv_label_create(ui_scrSetting);
    lv_obj_set_width(ui_lbSettingTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbSettingTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbSettingTitle, 0);
    lv_obj_set_y(ui_lbSettingTitle, -215);
    lv_obj_set_align(ui_lbSettingTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbSettingTitle, "SETTING");
    lv_obj_set_style_text_font(ui_lbSettingTitle, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ibtSettingBackToMain = lv_imgbtn_create(ui_scrSetting);
    lv_imgbtn_set_src(ui_ibtSettingBackToMain, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_imgsettingbackicon_png, NULL);
    lv_obj_set_width(ui_ibtSettingBackToMain, 50);
    lv_obj_set_height(ui_ibtSettingBackToMain, 50);
    lv_obj_set_x(ui_ibtSettingBackToMain, 372);
    lv_obj_set_y(ui_ibtSettingBackToMain, -212);
    lv_obj_set_align(ui_ibtSettingBackToMain, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ibtSettingBackToMain, ui_event_ibtSettingBackToMain, LV_EVENT_ALL, NULL);

}

void ui_scrSetting_screen_destroy(void)
{
    if(ui_scrSetting) lv_obj_del(ui_scrSetting);

    // NULL screen variables
    ui_scrSetting = NULL;
    ui_imgSettingBackground = NULL;
    ui_lbSettingTitle = NULL;
    ui_ibtSettingBackToMain = NULL;

}
