// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRMANUALCONTROL22_H
#define UI_SCRMANUALCONTROL22_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrManualControl22
extern void ui_scrManualControl22_screen_init(void);
extern void ui_scrManualControl22_screen_destroy(void);
extern void ui_event_scrManualControl22(lv_event_t * e);
extern lv_obj_t * ui_scrManualControl22;
extern lv_obj_t * ui_scrmanual2robotnchrgimg;
extern lv_obj_t * ui_scrmanual2guidelabel;
extern lv_obj_t * ui_scrmanual2vmologo;
extern void ui_event_scrmanual2backtomainbutton(lv_event_t * e);
extern lv_obj_t * ui_scrmanual2backtomainbutton;
extern lv_obj_t * ui_scrmanual2btgrpcontainer;
extern lv_obj_t * ui_chooses1container;
extern void ui_event_chooses1container_button(lv_event_t * e);
extern lv_obj_t * ui_chooses2container;
extern void ui_event_chooses2container_button(lv_event_t * e);
extern lv_obj_t * ui_chooses3container;
extern void ui_event_chooses3container_button(lv_event_t * e);
extern lv_obj_t * ui_chooses4container;
extern void ui_event_chooses4container_button(lv_event_t * e);
extern lv_obj_t * ui_chooses5container;
extern void ui_event_chooses5container_button(lv_event_t * e);
extern lv_obj_t * ui_scrmanual2infoslotcontainer;
extern lv_obj_t * ui_scrmanual2infoslot1label;
extern lv_obj_t * ui_scrmanual2infoslot2label;
extern lv_obj_t * ui_scrmanual2infoslot3label;
extern lv_obj_t * ui_scrmanual2infoslot4label;
extern lv_obj_t * ui_scrmanual2infoslot5label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

