// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRMAINSLOT_H
#define UI_SCRMAINSLOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrMainSlot
extern void ui_scrMainSlot_screen_init(void);
extern void ui_scrMainSlot_screen_destroy(void);
extern lv_obj_t * ui_scrMainSlot;
extern lv_obj_t * ui_menucontainer2;
extern lv_obj_t * ui_leftsidebar2;
extern lv_obj_t * ui_batterycontainer2;
extern lv_obj_t * ui_batteryicon2;
extern lv_obj_t * ui_batterylabel2;
extern void ui_event_batterybtn2(lv_event_t * e);
extern lv_obj_t * ui_batterybtn2;
extern lv_obj_t * ui_settingcontainer2;
extern lv_obj_t * ui_settingicon2;
extern lv_obj_t * ui_settinglabel2;
extern lv_obj_t * ui_infocontainer2;
extern lv_obj_t * ui_infoicon2;
extern lv_obj_t * ui_infolabel2;
extern lv_obj_t * ui_manualcontainer2;
extern lv_obj_t * ui_maunicon2;
extern lv_obj_t * ui_manlabel2;
extern void ui_event_manualbtn(lv_event_t * e);
extern lv_obj_t * ui_manualbtn;
extern void ui_event_manualbtn1(lv_event_t * e);
extern lv_obj_t * ui_manualbtn1;
extern lv_obj_t * ui_slotbatterysttcontainer2;
extern lv_obj_t * ui_slotbatterystt11;
extern lv_obj_t * ui_slotbatterystt12;
extern lv_obj_t * ui_slotbatterystt13;
extern lv_obj_t * ui_slotbatterystt14;
extern lv_obj_t * ui_slotbatterystt15;
extern lv_obj_t * ui_lasttimecontainer1;
extern lv_obj_t * ui_slottitle;
extern lv_obj_t * ui_slotdetailvalue;
extern lv_obj_t * ui_vmochargeralone;
extern void ui_event_vmologo5(lv_event_t * e);
extern lv_obj_t * ui_vmologo5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

