// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SQUARELINE_RBCS_HMI

#ifndef UI_SCRPROCESS_H
#define UI_SCRPROCESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scrProcess
extern void ui_scrProcess_screen_init(void);
extern void ui_scrProcess_screen_destroy(void);
extern lv_obj_t * ui_scrProcess;
extern lv_obj_t * ui_vmologo4;
extern lv_obj_t * ui_runtimecontainer;
extern lv_obj_t * ui_runtimepanel;
extern lv_obj_t * ui_runtimetitle;
extern lv_obj_t * ui_runtimevalue;
extern lv_obj_t * ui_slotbatterysttcontainer1;
extern lv_obj_t * ui_slotbatterystt6;
extern lv_obj_t * ui_slotbatterystt7;
extern lv_obj_t * ui_slotbatterystt8;
extern lv_obj_t * ui_slotbatterystt9;
extern lv_obj_t * ui_slotbatterystt10;
extern lv_obj_t * ui_robotandcharge1;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

